export type AdminModuleConfig = {
  id: string;
  title: string;
  description: string;
  apiEndpoint: string;
  erpModuleId?: string;
  gestorEndpoint?: string;
  exportType?: string;
  breadcrumbs?: { label: string; href?: string }[];
};

export const ADMIN_MODULES: Record<string, AdminModuleConfig> = {
  dashboard: {
    id: "dashboard",
    title: "Dashboard Executivo",
    description: "Visão executiva consolidada — KPIs, gráficos e insights em tempo real.",
    apiEndpoint: "dashboard",
    erpModuleId: "dashboard",
  },
  empresa: {
    id: "empresa",
    title: "Empresa",
    description: "Visão corporativa EcoPet — unidades de negócio e indicadores globais.",
    apiEndpoint: "empresa",
    erpModuleId: "empresa",
  },
  operacao: {
    id: "operacao",
    title: "Operação",
    description: "Aprovações, denúncias, tickets críticos e SLA operacional.",
    apiEndpoint: "operacao",
    erpModuleId: "operacao",
  },
  bi: {
    id: "bi",
    title: "Business Intelligence",
    description: "BI corporativo — receita, segmentação, previsões e anomalias.",
    apiEndpoint: "bi",
    erpModuleId: "bi",
  },
  financeiro: {
    id: "financeiro",
    title: "Financeiro ERP",
    description: "Contas a pagar/receber, fluxo de caixa, comissões e conciliação.",
    apiEndpoint: "finance",
    erpModuleId: "financeiro",
  },
  contabil: {
    id: "contabil",
    title: "Contabilidade",
    description: "DRE, balancete, lançamentos e exportação para contador.",
    apiEndpoint: "accounting",
    erpModuleId: "contabil",
  },
  controladoria: {
    id: "controladoria",
    title: "Controladoria",
    description: "Margem, EBITDA, ROI, forecast e orçamento vs realizado.",
    apiEndpoint: "controladoria",
    erpModuleId: "controladoria",
  },
  juridico: {
    id: "juridico",
    title: "Jurídico",
    description: "Contratos, LGPD, compliance e riscos jurídicos.",
    apiEndpoint: "legal",
    erpModuleId: "juridico",
  },
  rh: {
    id: "rh",
    title: "Recursos Humanos",
    description: "Colaboradores, departamentos, organograma e acessos.",
    apiEndpoint: "hr",
    erpModuleId: "rh",
  },
  ti: {
    id: "ti",
    title: "TI / Infraestrutura",
    description: "Saúde do sistema, logs, deploys e performance.",
    apiEndpoint: "it",
    erpModuleId: "ti",
  },
  ciberseguranca: {
    id: "ciberseguranca",
    title: "Cibersegurança",
    description: "Sessões, autenticação, bloqueios e auditoria de segurança.",
    apiEndpoint: "ciberseguranca",
    erpModuleId: "ciberseguranca",
  },
  seguranca: {
    id: "seguranca",
    title: "Segurança",
    description: "Sessões, login, LGPD, eventos suspeitos e auditoria de acesso.",
    apiEndpoint: "seguranca",
    erpModuleId: "seguranca",
  },
  inovacao: {
    id: "inovacao",
    title: "Inovação e IA",
    description: "Agentes, prompts e experimentos de IA.",
    apiEndpoint: "innovation",
    erpModuleId: "inovacao",
  },
  "ia-center": {
    id: "ia-center",
    title: "IA Center",
    description: "Modelos, agentes, custos, tokens e benchmarks de IA.",
    apiEndpoint: "innovation",
    erpModuleId: "ia-center",
  },
  ia: {
    id: "ia",
    title: "IA Center",
    description: "Agentes, prompts, modelos, custos, logs e status dos providers.",
    apiEndpoint: "ia",
    erpModuleId: "ia",
  },
  marketing: {
    id: "marketing",
    title: "Marketing",
    description: "Campanhas, conversões, CAC e ROI de marketing.",
    apiEndpoint: "marketing",
    erpModuleId: "marketing",
  },
  administrativo: {
    id: "administrativo",
    title: "Administrativo",
    description: "Tarefas, processos e comunicados internos.",
    apiEndpoint: "administrative",
    erpModuleId: "administrativo",
  },
  permissoes: {
    id: "permissoes",
    title: "Acessos e Permissões",
    description: "RBAC, perfis e controle granular de acesso.",
    apiEndpoint: "permissions",
    erpModuleId: "permissoes",
  },
  laboratorio: {
    id: "laboratorio",
    title: "Laboratório",
    description: "Feature flags, A/B tests e experimentos controlados.",
    apiEndpoint: "laboratory",
    erpModuleId: "laboratorio",
  },
  comercial: {
    id: "comercial",
    title: "Comercial / CRM",
    description: "Pipeline, leads, propostas e funil de vendas.",
    apiEndpoint: "commercial",
    erpModuleId: "comercial",
  },
  crm: {
    id: "crm",
    title: "CRM",
    description: "Gestão de relacionamento com clientes e parceiros.",
    apiEndpoint: "commercial",
    erpModuleId: "crm",
  },
  tecnico: {
    id: "tecnico",
    title: "Técnico / Operações",
    description: "Suporte operacional, SLA e qualidade.",
    apiEndpoint: "technical",
    erpModuleId: "tecnico",
  },
  suporte: {
    id: "suporte",
    title: "Suporte",
    description: "Tickets, filas, SLA e base de conhecimento.",
    apiEndpoint: "support",
    erpModuleId: "suporte",
  },
  integracoes: {
    id: "integracoes",
    title: "Integrações",
    description: "Health check, webhooks, latência e logs de sync.",
    apiEndpoint: "integrations",
    erpModuleId: "integracoes",
  },
  analytics: {
    id: "analytics",
    title: "Analytics",
    description: "Eventos, coortes, retenção e métricas cross-módulo.",
    apiEndpoint: "analytics",
    erpModuleId: "analytics",
  },
  automacoes: {
    id: "automacoes",
    title: "Centro de Automações",
    description: "Workflows tipo Zapier — fluxos e execuções.",
    apiEndpoint: "automacoes",
    erpModuleId: "automacoes",
  },
  "data-center": {
    id: "data-center",
    title: "Data Center",
    description: "Importação, exportação, backups e governança de dados.",
    apiEndpoint: "data-center",
    erpModuleId: "data-center",
  },
  produto: {
    id: "produto",
    title: "Produto",
    description: "Roadmap, backlog, releases e feedback.",
    apiEndpoint: "produto",
    erpModuleId: "produto",
  },
  assistente: {
    id: "assistente",
    title: "Assistente Executivo IA",
    description: "Copiloto administrativo com respostas baseadas em dados reais.",
    apiEndpoint: "assistant",
    erpModuleId: "bi",
  },
  marketplace: {
    id: "marketplace",
    title: "Marketplace",
    description: "Produtos, estoque, pedidos e margem.",
    gestorEndpoint: "marketplace",
    apiEndpoint: "marketplace",
    erpModuleId: "marketplace",
    exportType: "products",
  },
  social: {
    id: "social",
    title: "Social / Comunidade",
    description: "Feed, engajamento e moderação.",
    gestorEndpoint: "social",
    apiEndpoint: "social",
    erpModuleId: "social",
  },
  audit: {
    id: "audit",
    title: "Auditoria / Logs",
    description: "Trilha de auditoria completa com exportação.",
    apiEndpoint: "audit",
    erpModuleId: "audit",
    exportType: "audit",
  },
  auditoria: {
    id: "auditoria",
    title: "Auditoria",
    description: "Timeline de ações, logs críticos e exportação CSV.",
    apiEndpoint: "auditoria",
    erpModuleId: "auditoria",
    exportType: "audit",
  },
  configuracoes: {
    id: "configuracoes",
    title: "Configurações",
    description: "Papéis internos, matriz de permissões e configurações da plataforma.",
    apiEndpoint: "configuracoes",
    erpModuleId: "configuracoes",
  },
  partners: {
    id: "partners",
    title: "Parceiros",
    description: "Gestão comercial e operacional de parceiros.",
    gestorEndpoint: "partners",
    apiEndpoint: "partners",
    erpModuleId: "partners",
    exportType: "partners",
  },
  ngos: {
    id: "ngos",
    title: "ONGs",
    description: "Organizações, adoções e campanhas.",
    gestorEndpoint: "ongs",
    apiEndpoint: "ngos",
    erpModuleId: "ngos",
    exportType: "ongs",
  },
  moderacao: {
    id: "moderacao",
    title: "Moderação",
    description: "Fila unificada, posts, comentários, perfis e regras automáticas.",
    apiEndpoint: "moderacao",
    erpModuleId: "moderacao",
    breadcrumbs: [{ label: "Admin", href: "/admin" }, { label: "Moderação" }],
  },
  contas: {
    id: "contas",
    title: "Gestão de Contas",
    description: "Advertências, suspensões, bloqueios, sessões e histórico de punições.",
    apiEndpoint: "contas",
    erpModuleId: "contas",
    breadcrumbs: [{ label: "Admin", href: "/admin" }, { label: "Contas" }],
  },
  comunidade: {
    id: "comunidade",
    title: "Comunidade",
    description: "Grupos, mensagens, denúncias e membros.",
    apiEndpoint: "comunidade",
    erpModuleId: "comunidade",
    breadcrumbs: [{ label: "Admin", href: "/admin" }, { label: "Comunidade" }],
  },
  lojas: {
    id: "lojas",
    title: "Lojas e Parceiros",
    description: "Aprovação, suspensão, documentos e pedidos problemáticos.",
    apiEndpoint: "lojas",
    erpModuleId: "lojas",
    breadcrumbs: [{ label: "Admin", href: "/admin" }, { label: "Lojas" }],
  },
  perfis: {
    id: "perfis",
    title: "Revisão de Perfis",
    description: "Foto, bio, links, documentos e verificação.",
    apiEndpoint: "perfis",
    erpModuleId: "perfis",
    breadcrumbs: [{ label: "Admin", href: "/admin" }, { label: "Perfis" }],
  },
  mensagens: {
    id: "mensagens",
    title: "Mensagens",
    description: "Moderação de chat, denúncias e conversas.",
    apiEndpoint: "mensagens",
    erpModuleId: "mensagens",
    breadcrumbs: [{ label: "Admin", href: "/admin" }, { label: "Mensagens" }],
  },
  reputacao: {
    id: "reputacao",
    title: "Reputação",
    description: "Avaliações, fraudes, ranking de risco e respostas.",
    apiEndpoint: "reputacao",
    erpModuleId: "reputacao",
    breadcrumbs: [{ label: "Admin", href: "/admin" }, { label: "Reputação" }],
  },
  incidentes: {
    id: "incidentes",
    title: "Incidentes e Segurança",
    description: "Timeline, severidade, evidências e relatórios.",
    apiEndpoint: "incidentes",
    erpModuleId: "incidentes",
    breadcrumbs: [{ label: "Admin", href: "/admin" }, { label: "Incidentes" }],
  },
  governanca: {
    id: "governanca",
    title: "Governança e Compliance",
    description: "LGPD, consentimentos, termos, auditoria e retenção.",
    apiEndpoint: "governanca",
    erpModuleId: "governanca",
    breadcrumbs: [{ label: "Admin", href: "/admin" }, { label: "Governança" }],
  },
  eventos: {
    id: "eventos",
    title: "Event Bus",
    description: "Eventos internos da plataforma — atores, entidades e severidade.",
    apiEndpoint: "events",
    erpModuleId: "eventos",
  },
  webhooks: {
    id: "webhooks",
    title: "Webhooks",
    description: "Recebimentos, processamento idempotente e reprocessamento.",
    apiEndpoint: "webhooks",
    erpModuleId: "webhooks",
  },
  jobs: {
    id: "jobs",
    title: "Jobs",
    description: "Fila de jobs — status, tentativas e retry.",
    apiEndpoint: "jobs",
    erpModuleId: "jobs",
  },
  filas: {
    id: "filas",
    title: "Filas",
    description: "Visão operacional das filas de processamento.",
    apiEndpoint: "jobs",
    erpModuleId: "filas",
  },
  workflows: {
    id: "workflows",
    title: "Workflows",
    description: "Motor de workflows — gatilhos, ações e execuções.",
    apiEndpoint: "workflows",
    erpModuleId: "workflows",
  },
  "logs-integracao": {
    id: "logs-integracao",
    title: "Logs de Integração",
    description: "PlatformIntegrationLog — auditoria de sync e webhooks.",
    apiEndpoint: "integrations/logs",
    erpModuleId: "logs-integracao",
  },
};

export function getAdminModule(id: string): AdminModuleConfig | undefined {
  return ADMIN_MODULES[id];
}
