import type { LucideIcon } from "lucide-react";
import {
  LayoutDashboard,
  DollarSign,
  FileText,
  Scale,
  Users,
  Cpu,
  Lightbulb,
  Megaphone,
  FolderKanban,
  Lock,
  FlaskConical,
  TrendingUp,
  Wrench,
  Plug,
  UserCheck,
  Building2,
  Heart,
  ShoppingBag,
  Share2,
  Settings,
  Shield,
  ClipboardList,
  Calendar,
  LineChart,
  BarChart3,
  Headphones,
  ShieldAlert,
  Bot,
  Package,
  Activity,
  Workflow,
  Database,
  Sparkles,
} from "lucide-react";

export type AdminNavItem = {
  href: string;
  label: string;
  icon: LucideIcon;
  exact?: boolean;
  group: string;
};

export const ADMIN_NAV: AdminNavItem[] = [
  { href: "/admin", label: "Dashboard Executivo", icon: LayoutDashboard, exact: true, group: "Executivo & BI" },
  { href: "/admin/bi", label: "Business Intelligence", icon: LineChart, group: "Executivo & BI" },
  { href: "/admin/analytics", label: "Analytics", icon: Activity, group: "Executivo & BI" },
  { href: "/admin/assistente", label: "Assistente IA", icon: Sparkles, group: "Executivo & BI" },
  { href: "/admin/financeiro", label: "Financeiro ERP", icon: DollarSign, group: "Financeiro" },
  { href: "/admin/contabil", label: "Contabilidade", icon: FileText, group: "Financeiro" },
  { href: "/admin/controladoria", label: "Controladoria", icon: BarChart3, group: "Financeiro" },
  { href: "/admin/comercial", label: "Comercial / CRM", icon: TrendingUp, group: "Comercial" },
  { href: "/admin/crm", label: "CRM", icon: TrendingUp, group: "Comercial" },
  { href: "/admin/marketing", label: "Marketing", icon: Megaphone, group: "Comercial" },
  { href: "/admin/juridico", label: "Jurídico", icon: Scale, group: "Compliance" },
  { href: "/admin/ciberseguranca", label: "Cibersegurança", icon: ShieldAlert, group: "Compliance" },
  { href: "/admin/rh", label: "Recursos Humanos", icon: Users, group: "Pessoas" },
  { href: "/admin/administrativo", label: "Administrativo", icon: FolderKanban, group: "Operações" },
  { href: "/admin/tecnico", label: "Técnico / Operações", icon: Wrench, group: "Operações" },
  { href: "/admin/suporte", label: "Suporte", icon: Headphones, group: "Operações" },
  { href: "/admin/ti", label: "TI / Infraestrutura", icon: Cpu, group: "Tecnologia" },
  { href: "/admin/integracoes", label: "Integrações", icon: Plug, group: "Tecnologia" },
  { href: "/admin/data-center", label: "Data Center", icon: Database, group: "Tecnologia" },
  { href: "/admin/inovacao", label: "Inovação", icon: Lightbulb, group: "IA & Inovação" },
  { href: "/admin/ia-center", label: "IA Center", icon: Bot, group: "IA & Inovação" },
  { href: "/admin/ai", label: "Plataforma AI", icon: Sparkles, group: "IA & Inovação" },
  { href: "/admin/laboratorio", label: "Laboratório", icon: FlaskConical, group: "IA & Inovação" },
  { href: "/admin/automacoes", label: "Automações", icon: Workflow, group: "IA & Inovação" },
  { href: "/admin/produto", label: "Produto", icon: Package, group: "Produto" },
  { href: "/admin/users", label: "Usuários", icon: Users, group: "Plataforma" },
  { href: "/admin/partners", label: "Parceiros", icon: Building2, group: "Plataforma" },
  { href: "/admin/ngos", label: "ONGs", icon: Heart, group: "Plataforma" },
  { href: "/admin/marketplace", label: "Marketplace", icon: ShoppingBag, group: "Plataforma" },
  { href: "/admin/social", label: "Social", icon: Share2, group: "Plataforma" },
  { href: "/admin/approvals", label: "Aprovações", icon: UserCheck, group: "Plataforma" },
  { href: "/admin/orders", label: "Pedidos", icon: ClipboardList, group: "Plataforma" },
  { href: "/admin/appointments", label: "Agendamentos", icon: Calendar, group: "Plataforma" },
  { href: "/admin/permissoes", label: "Permissões", icon: Lock, group: "Governança" },
  { href: "/admin/audit", label: "Auditoria", icon: Shield, group: "Governança" },
  { href: "/admin/settings", label: "Configurações", icon: Settings, group: "Governança" },
];

export const ADMIN_NAV_GROUPS = [...new Set(ADMIN_NAV.map((n) => n.group))];
