import type { LucideIcon } from "lucide-react";
import {
  LayoutDashboard,
  DollarSign,
  FileText,
  Scale,
  Users,
  Cpu,
  Lightbulb,
  Megaphone,
  FolderKanban,
  Lock,
  FlaskConical,
  TrendingUp,
  Wrench,
  Plug,
  UserCheck,
  Building2,
  Heart,
  ShoppingBag,
  Share2,
  Settings,
  Shield,
  ClipboardList,
  Calendar,
  LineChart,
  BarChart3,
  Headphones,
  ShieldAlert,
  Bot,
  Package,
  Activity,
  Workflow,
  Database,
  ShieldCheck,
  UserX,
  MessagesSquare,
  Store,
  BadgeCheck,
  MessageSquareWarning,
  Star,
  AlertTriangle,
  Gavel,
  Sparkles,
} from "lucide-react";

export type AdminNavItem = {
  href: string;
  label: string;
  icon: LucideIcon;
  exact?: boolean;
  group: string;
};

export const ADMIN_NAV: AdminNavItem[] = [
  { href: "/admin", label: "Dashboard Executivo", icon: LayoutDashboard, exact: true, group: "Executivo" },
  { href: "/admin/empresa", label: "Empresa", icon: Building2, group: "Executivo" },
  { href: "/admin/operacao", label: "Operação", icon: ClipboardList, group: "Executivo" },
  { href: "/admin/bi", label: "Business Intelligence", icon: LineChart, group: "Executivo" },
  { href: "/admin/analytics", label: "Analytics", icon: Activity, group: "Executivo" },
  { href: "/admin/financeiro", label: "Financeiro", icon: DollarSign, group: "Financeiro" },
  { href: "/admin/contabil", label: "Contabilidade", icon: FileText, group: "Financeiro" },
  { href: "/admin/controladoria", label: "Controladoria", icon: BarChart3, group: "Financeiro" },
  { href: "/admin/comercial", label: "Comercial", icon: TrendingUp, group: "Comercial" },
  { href: "/admin/crm", label: "CRM", icon: TrendingUp, group: "Comercial" },
  { href: "/admin/marketing", label: "Marketing", icon: Megaphone, group: "Comercial" },
  { href: "/admin/juridico", label: "Jurídico", icon: Scale, group: "Compliance" },
  { href: "/admin/seguranca", label: "Segurança", icon: ShieldAlert, group: "Compliance" },
  { href: "/admin/ciberseguranca", label: "Cibersegurança (legado)", icon: ShieldAlert, group: "Compliance" },
  { href: "/admin/rh", label: "Recursos Humanos", icon: Users, group: "Pessoas" },
  { href: "/admin/produto", label: "Produto", icon: Package, group: "Produto" },
  { href: "/admin/ti", label: "TI", icon: Cpu, group: "Tecnologia" },
  { href: "/admin/integracoes", label: "Integrações", icon: Plug, group: "Integração & Automação" },
  { href: "/admin/automacoes", label: "Automações", icon: Workflow, group: "Integração & Automação" },
  { href: "/admin/workflows", label: "Workflows", icon: Workflow, group: "Integração & Automação" },
  { href: "/admin/eventos", label: "Eventos", icon: Activity, group: "Integração & Automação" },
  { href: "/admin/webhooks", label: "Webhooks", icon: Plug, group: "Integração & Automação" },
  { href: "/admin/jobs", label: "Jobs", icon: Cpu, group: "Integração & Automação" },
  { href: "/admin/filas", label: "Filas", icon: Database, group: "Integração & Automação" },
  { href: "/admin/logs-integracao", label: "Logs integração", icon: FileText, group: "Integração & Automação" },
  { href: "/admin/data-center", label: "Data Center", icon: Database, group: "Tecnologia" },
  { href: "/admin/ia", label: "IA Center", icon: Bot, group: "IA & Automação" },
  { href: "/admin/ia-center", label: "IA Center (legado)", icon: Bot, group: "IA & Automação" },
  { href: "/admin/ai", label: "Plataforma AI", icon: Sparkles, group: "IA & Automação" },
  { href: "/admin/laboratorio", label: "Laboratório", icon: FlaskConical, group: "IA & Automação" },
  { href: "/admin/inovacao", label: "Inovação", icon: Lightbulb, group: "IA & Automação" },
  { href: "/admin/suporte", label: "Suporte", icon: Headphones, group: "Operações" },
  { href: "/admin/moderacao", label: "Moderação", icon: ShieldCheck, group: "Moderação & Comunidade" },
  { href: "/admin/contas", label: "Contas", icon: UserX, group: "Moderação & Comunidade" },
  { href: "/admin/comunidade", label: "Comunidade", icon: MessagesSquare, group: "Moderação & Comunidade" },
  { href: "/admin/lojas", label: "Lojas", icon: Store, group: "Moderação & Comunidade" },
  { href: "/admin/perfis", label: "Perfis", icon: BadgeCheck, group: "Moderação & Comunidade" },
  { href: "/admin/mensagens", label: "Mensagens", icon: MessageSquareWarning, group: "Moderação & Comunidade" },
  { href: "/admin/reputacao", label: "Reputação", icon: Star, group: "Moderação & Comunidade" },
  { href: "/admin/incidentes", label: "Incidentes", icon: AlertTriangle, group: "Moderação & Comunidade" },
  { href: "/admin/governanca", label: "Governança", icon: Gavel, group: "Moderação & Comunidade" },
  { href: "/admin/administrativo", label: "Administrativo", icon: FolderKanban, group: "Operações" },
  { href: "/admin/tecnico", label: "Técnico", icon: Wrench, group: "Operações" },
  { href: "/admin/users", label: "Usuários", icon: Users, group: "Plataforma" },
  { href: "/admin/partners", label: "Parceiros", icon: Building2, group: "Plataforma" },
  { href: "/admin/ngos", label: "ONGs", icon: Heart, group: "Plataforma" },
  { href: "/admin/marketplace", label: "Marketplace", icon: ShoppingBag, group: "Plataforma" },
  { href: "/admin/social", label: "Social", icon: Share2, group: "Plataforma" },
  { href: "/admin/approvals", label: "Aprovações", icon: UserCheck, group: "Plataforma" },
  { href: "/admin/orders", label: "Pedidos", icon: ClipboardList, group: "Plataforma" },
  { href: "/admin/appointments", label: "Agendamentos", icon: Calendar, group: "Plataforma" },
  { href: "/admin/permissoes", label: "Permissões", icon: Lock, group: "Governança" },
  { href: "/admin/auditoria", label: "Auditoria", icon: Shield, group: "Governança" },
  { href: "/admin/audit", label: "Auditoria (legado)", icon: Shield, group: "Governança" },
  { href: "/admin/configuracoes", label: "Configurações", icon: Settings, group: "Governança" },
  { href: "/admin/settings", label: "Configurações (legado)", icon: Settings, group: "Governança" },
  { href: "/admin/assistente", label: "Assistente IA", icon: Sparkles, group: "Executivo" },
];

export const ADMIN_NAV_GROUPS = [...new Set(ADMIN_NAV.map((n) => n.group))];
