import type { PartnerErpModuleId } from "./types";
import type { PartnerErpResource } from "./permissions";

/** Mapeamento módulo ERP → resource RBAC (1:1). */
export const PARTNER_ERP_MODULE_RESOURCE: Record<PartnerErpModuleId, PartnerErpResource> = {
  dashboard: "dashboard",
  bi: "dashboard",
  financeiro: "financeiro",
  contabil: "contabil",
  comercial: "comercial",
  crm: "crm",
  vendas: "vendas",
  analytics: "analytics",
  marketplace: "marketplace",
  rh: "rh",
  juridico: "juridico",
  administrativo: "administrativo",
  compras: "compras",
  fornecedores: "fornecedores",
  permissoes: "permissoes",
  infraestrutura: "infraestrutura",
  ti: "ti",
  equipamentos: "equipamentos",
  iot: "iot",
  automacoes: "automacoes",
  ia: "ia",
  marketing: "marketing",
  social: "social",
  clientes: "clientes",
  fidelidade: "fidelidade",
  veterinario: "veterinario",
  loja: "loja",
  integracoes: "integracoes",
  laboratorio: "laboratorio",
  suporte: "suporte",
  parcerias: "parcerias",
};

export const PARTNER_ERP_RESOURCE_LABELS: Record<PartnerErpResource, string> = {
  dashboard: "Dashboard / BI",
  rh: "Recursos Humanos",
  juridico: "Jurídico",
  administrativo: "Administrativo",
  compras: "Compras",
  fornecedores: "Fornecedores",
  permissoes: "Permissões",
  financeiro: "Financeiro",
  contabil: "Contábil",
  comercial: "Comercial",
  crm: "CRM",
  vendas: "Vendas",
  analytics: "Analytics",
  infraestrutura: "Infraestrutura",
  ti: "TI",
  equipamentos: "Equipamentos",
  iot: "IoT",
  automacoes: "Automações",
  ia: "Inteligência Artificial",
  marketing: "Marketing",
  social: "Rede Social",
  clientes: "Relacionamento",
  fidelidade: "Fidelização",
  marketplace: "Marketplace",
  veterinario: "Veterinário",
  loja: "Loja Física",
  integracoes: "Integrações",
  laboratorio: "Laboratório",
  suporte: "Suporte",
  parcerias: "Parcerias",
};
