import type { Notification, AiSummary } from "./types";

/**
 * Lista mockada — substituir por fetchNotifications() quando a API estiver pronta.
 */
export const MOCK_NOTIFICATIONS: Notification[] = [
  // IA
  {
    id: "n1",
    category: "ai",
    title: "Sugestão da IA Pet",
    description: "Com base no perfil da Luna, recomendamos aumentar a hidratação nos dias mais quentes.",
    createdAt: "2026-05-24T09:15:00.000Z",
    read: false,
    action: { label: "Ver sugestão", href: "/ia" },
    meta: { petId: "luna" },
  },
  {
    id: "n2",
    category: "ai",
    title: "Alerta inteligente",
    description: "Padrão de coceira detectado nos últimos 7 dias — considere consulta dermatológica.",
    createdAt: "2026-05-24T08:00:00.000Z",
    read: false,
    action: { label: "Abrir triagem", href: "/ia" },
  },
  {
    id: "n3",
    category: "ai",
    title: "Recomendação personalizada",
    description: "Ração premium grain-free combina com a dieta registrada do Thor.",
    createdAt: "2026-05-23T14:30:00.000Z",
    read: true,
    action: { label: "Ver produto", href: "/marketplace" },
  },
  {
    id: "n4",
    category: "ai",
    title: "Lembrete automático",
    description: "Hora do passeio matinal — Thor costuma ser mais ativo antes das 9h.",
    createdAt: "2026-05-23T07:00:00.000Z",
    read: true,
  },
  // Saúde
  {
    id: "n5",
    category: "health",
    title: "Vacina próxima",
    description: "A vacina V10 da Luna vence em 15 dias. Agende com antecedência.",
    createdAt: "2026-05-24T10:00:00.000Z",
    read: false,
    action: { label: "Agendar", href: "/pets" },
    meta: { petId: "luna", type: "vaccine" },
  },
  {
    id: "n6",
    category: "health",
    title: "Consulta agendada",
    description: "Consulta de rotina com Dr. Carlos Mendes — 28/05 às 15h.",
    createdAt: "2026-05-23T16:45:00.000Z",
    read: false,
    action: { label: "Ver detalhes", href: "/veterinarios" },
  },
  {
    id: "n7",
    category: "health",
    title: "Medicamento",
    description: "Lembrete: antipulgas da Luna — próxima dose amanhã.",
    createdAt: "2026-05-22T20:00:00.000Z",
    read: true,
    action: { label: "Prontuário", href: "/pets" },
  },
  {
    id: "n8",
    category: "health",
    title: "Exame disponível",
    description: "Resultado do hemograma do Thor já está no prontuário.",
    createdAt: "2026-05-22T11:20:00.000Z",
    read: true,
    action: { label: "Ver exame", href: "/pets" },
  },
  {
    id: "n9",
    category: "health",
    title: "Prontuário atualizado",
    description: "Nova anotação de peso registrada para Luna: 12,4 kg.",
    createdAt: "2026-05-21T09:00:00.000Z",
    read: true,
  },
  // Marketplace
  {
    id: "n10",
    category: "marketplace",
    title: "Pedido aprovado",
    description: "Seu pedido #ECO-4821 foi confirmado e está sendo preparado.",
    createdAt: "2026-05-24T11:30:00.000Z",
    read: false,
    action: { label: "Rastrear", href: "/marketplace" },
  },
  {
    id: "n11",
    category: "marketplace",
    title: "Pedido enviado",
    description: "Pacote a caminho! Previsão de entrega: 26/05.",
    createdAt: "2026-05-23T18:00:00.000Z",
    read: false,
    action: { label: "Ver pedido", href: "/marketplace" },
  },
  {
    id: "n12",
    category: "marketplace",
    title: "Promoção exclusiva",
    description: "15% OFF em ração premium para assinantes ECOPET — válido até domingo.",
    createdAt: "2026-05-23T12:00:00.000Z",
    read: true,
    action: { label: "Aproveitar", href: "/marketplace" },
  },
  {
    id: "n13",
    category: "marketplace",
    title: "Assinatura renovada",
    description: "Plano Premium renovado com sucesso. Próxima cobrança em 24/06.",
    createdAt: "2026-05-20T08:00:00.000Z",
    read: true,
    action: { label: "Ver plano", href: "/assinatura" },
  },
  {
    id: "n14",
    category: "marketplace",
    title: "Produto recomendado",
    description: "Shampoo hipoalergênico — ideal para pets com pele sensível como a Luna.",
    createdAt: "2026-05-19T15:00:00.000Z",
    read: true,
    action: { label: "Ver produto", href: "/marketplace" },
  },
  // Serviços
  {
    id: "n15",
    category: "services",
    title: "Banho e tosa agendado",
    description: "Pet Shop Amigo — 25/05 às 10h para Luna.",
    createdAt: "2026-05-24T07:45:00.000Z",
    read: false,
    action: { label: "Confirmar", href: "/marketplace" },
  },
  {
    id: "n16",
    category: "services",
    title: "Consulta veterinária",
    description: "Teleconsulta confirmada para 27/05 às 19h.",
    createdAt: "2026-05-23T09:30:00.000Z",
    read: true,
    action: { label: "Entrar na sala", href: "/veterinarios" },
  },
  {
    id: "n17",
    category: "services",
    title: "Orçamento personalizado recebido",
    description: "3 prestadores enviaram propostas para transporte pet em SP.",
    createdAt: "2026-05-22T14:00:00.000Z",
    read: false,
    action: { label: "Comparar", href: "/marketplace" },
  },
  {
    id: "n18",
    category: "services",
    title: "Prestador respondeu",
    description: "Dog Walker SP aceitou sua solicitação de passeio recorrente.",
    createdAt: "2026-05-22T10:15:00.000Z",
    read: false,
    action: { label: "Ver resposta", href: "/chat" },
  },
  {
    id: "n19",
    category: "services",
    title: "Serviço concluído",
    description: "Banho e tosa da Luna finalizado. Avalie o prestador.",
    createdAt: "2026-05-18T16:00:00.000Z",
    read: true,
    action: { label: "Avaliar", href: "/marketplace" },
  },
  // Social
  {
    id: "n20",
    category: "social",
    title: "Curtida no seu post",
    description: "Seu reel da Luna recebeu 24 curtidas nas últimas 2 horas.",
    createdAt: "2026-05-24T12:00:00.000Z",
    read: false,
    action: { label: "Ver post", href: "/feed" },
  },
  {
    id: "n21",
    category: "social",
    title: "Novo comentário",
    description: "Ana comentou: \"Que fofa! Qual raça?\" no post do Thor.",
    createdAt: "2026-05-23T20:30:00.000Z",
    read: false,
    action: { label: "Responder", href: "/feed" },
  },
  {
    id: "n22",
    category: "social",
    title: "Novo seguidor",
    description: "Clínica VetCare começou a seguir você.",
    createdAt: "2026-05-23T13:00:00.000Z",
    read: true,
    action: { label: "Ver perfil", href: "/explore" },
  },
  {
    id: "n23",
    category: "social",
    title: "Menção ao pet",
    description: "Você foi marcado em uma foto com #LunaECOPET.",
    createdAt: "2026-05-22T17:45:00.000Z",
    read: true,
    action: { label: "Ver menção", href: "/feed" },
  },
  {
    id: "n24",
    category: "social",
    title: "Post recomendado",
    description: "Dica de enriquecimento ambiental para gatos — trending na comunidade.",
    createdAt: "2026-05-21T11:00:00.000Z",
    read: true,
    action: { label: "Explorar", href: "/explore" },
  },
  // Sistema
  {
    id: "n25",
    category: "system",
    title: "Cadastro aprovado",
    description: "Sua conta de tutor foi verificada com sucesso. Bem-vindo à ECOPET!",
    createdAt: "2026-05-20T10:00:00.000Z",
    read: true,
  },
  {
    id: "n26",
    category: "system",
    title: "Documento pendente",
    description: "Envie o comprovante de vacina da Luna para completar o prontuário.",
    createdAt: "2026-05-19T09:00:00.000Z",
    read: false,
    action: { label: "Enviar", href: "/pets" },
  },
  {
    id: "n27",
    category: "system",
    title: "Atualização de segurança",
    description: "Recomendamos ativar a verificação em duas etapas na sua conta.",
    createdAt: "2026-05-18T08:00:00.000Z",
    read: true,
    action: { label: "Configurar", href: "/configuracoes" },
  },
  {
    id: "n28",
    category: "system",
    title: "Aviso administrativo",
    description: "Manutenção programada em 30/05 das 2h às 4h — serviços podem ficar indisponíveis.",
    createdAt: "2026-05-17T12:00:00.000Z",
    read: true,
  },
];

/** Resumo IA mockado — futuramente gerado por /api/notifications/ai-summary */
export const MOCK_AI_SUMMARY: AiSummary = {
  headline: "Você tem 3 alertas importantes hoje",
  insights: [
    { id: "i1", text: "A vacina da Luna vence em 15 dias", priority: "high" },
    { id: "i2", text: "Há 2 recomendações de produtos com base no perfil do seu pet", priority: "medium" },
    { id: "i3", text: "1 prestador respondeu sua solicitação", priority: "medium" },
  ],
  generatedAt: "2026-05-24T12:00:00.000Z",
};
