import type { IoTDevice } from "./types";

export const IOT_DEVICES: IoTDevice[] = [
  {
    id: "iot1",
    name: "Coleira Smart Luna",
    type: "collar",
    petName: "Luna",
    status: "online",
    battery: 78,
    location: "Parque Ibirapuera — 200m",
    lastSync: "Há 2 min",
    alerts: 0,
    metrics: { steps: 8540, heartRate: 82, temperature: 38.2 },
  },
  {
    id: "iot2",
    name: "Alimentador Automático",
    type: "feeder",
    petName: "Luna",
    status: "online",
    battery: 100,
    location: "Casa — Sala",
    lastSync: "Há 5 min",
    alerts: 1,
    metrics: { portions: 2, remaining: "3 dias" },
  },
  {
    id: "iot3",
    name: "Câmera Pet Cam",
    type: "camera",
    petName: "Thor",
    status: "online",
    battery: 100,
    location: "Casa — Quintal",
    lastSync: "Tempo real",
    alerts: 0,
    metrics: { motion: "Inativo", recording: true },
  },
  {
    id: "iot4",
    name: "Balança Inteligente",
    type: "scale",
    petName: "Luna",
    status: "offline",
    battery: 12,
    location: "Casa — Banheiro",
    lastSync: "Há 2 dias",
    alerts: 1,
    metrics: { lastWeight: "28.1 kg", trend: "+0.1kg" },
  },
  {
    id: "iot5",
    name: "Bebedouro IoT",
    type: "water",
    petName: "Thor",
    status: "online",
    battery: 95,
    location: "Casa — Cozinha",
    lastSync: "Há 1 min",
    alerts: 0,
    metrics: { level: "85%", consumption: "1.2L/dia" },
  },
  {
    id: "iot6",
    name: "Monitor Saúde Cardíaco",
    type: "health",
    petName: "Luna",
    status: "warning",
    battery: 45,
    location: "Coleira integrada",
    lastSync: "Há 15 min",
    alerts: 2,
    metrics: { heartRate: 95, status: "Elevado leve" },
  },
];

export const IOT_ALERTS = [
  { id: "a1", device: "Balança Inteligente", message: "Bateria baixa (12%)", type: "warning" as const, time: "Há 1h" },
  { id: "a2", device: "Monitor Saúde", message: "Frequência cardíaca acima do normal", type: "health" as const, time: "Há 15 min" },
  { id: "a3", device: "Alimentador", message: "Ração acabando em ~3 dias", type: "info" as const, time: "Há 5 min" },
];

export const IOT_CATEGORIES = [
  { id: "collar", label: "Coleiras", count: 1 },
  { id: "camera", label: "Câmeras", count: 1 },
  { id: "feeder", label: "Alimentadores", count: 1 },
  { id: "water", label: "Bebedouros", count: 1 },
  { id: "scale", label: "Balanças", count: 1 },
  { id: "health", label: "Saúde", count: 1 },
  { id: "tracker", label: "Rastreadores", count: 0 },
  { id: "sensor", label: "Sensores", count: 0 },
];
