export {
  openSupportConversation,
  fetchConversationMessages,
  sendConversationMessage,
  markConversationRead,
  fetchConversations,
  createConversation,
  requestAiChat,
  initGuestChatSession,
  sendGuestMessage,
  convertGuestChat,
  type ApiChatMessage,
  type ApiConversation,
  type GuestMessage,
  type GuestSession,
} from "@/lib/chat/chat-api";
