/** Permissões futuras — apenas ADMIN hoje via requireAdmin. */
export const INTEGRATION_PERMISSIONS = {
  INTEGRATIONS_VIEW: "INTEGRATIONS_VIEW",
  INTEGRATIONS_MANAGE: "INTEGRATIONS_MANAGE",
  WORKFLOWS_VIEW: "WORKFLOWS_VIEW",
  WORKFLOWS_MANAGE: "WORKFLOWS_MANAGE",
  WEBHOOKS_REPROCESS: "WEBHOOKS_REPROCESS",
  JOBS_RETRY: "JOBS_RETRY",
  EVENTS_VIEW: "EVENTS_VIEW",
} as const;

export type IntegrationPermission = (typeof INTEGRATION_PERMISSIONS)[keyof typeof INTEGRATION_PERMISSIONS];
