/**
 * Catálogo oficial de variáveis de ambiente do EcoPet (apps/web + monorepo).
 * Fonte única para documentação, validação e scripts de deploy.
 */

export type EnvScope = "web" | "api" | "database" | "scripts";
export type EnvTier = "critical" | "recommended" | "optional";
export type DeployTarget = "Production" | "Preview" | "Development" | "CI";

export type EnvVarDefinition = {
  name: string;
  tier: EnvTier;
  scopes: EnvScope[];
  environments: DeployTarget[];
  purpose: string;
  usedIn: string[];
  example: string;
  secret?: boolean;
  /** Variável injetada automaticamente pela Vercel — não configurar manualmente */
  platform?: "vercel";
  /** Marcada como legada / pouco usada no runtime atual */
  legacy?: boolean;
};

export const ENV_REGISTRY: EnvVarDefinition[] = [
  // ─── Críticas (Vercel / produção) ───
  {
    name: "DATABASE_URL",
    tier: "critical",
    scopes: ["web", "api", "database"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Conexão PostgreSQL (Supabase pooler :6543) para Prisma em runtime",
    usedIn: [
      "packages/database/prisma/schema.prisma",
      "packages/database/src/client.ts",
      "apps/web/src/lib/env.ts",
    ],
    example:
      "postgresql://postgres.[ref]:[PASSWORD]@aws-0-sa-east-1.pooler.supabase.com:6543/postgres?pgbouncer=true&connection_limit=1",
    secret: true,
  },
  {
    name: "DIRECT_URL",
    tier: "critical",
    scopes: ["database", "scripts"],
    environments: ["Production", "Preview", "Development", "CI"],
    purpose: "Conexão direta PostgreSQL (:5432) para prisma migrate deploy",
    usedIn: ["packages/database/prisma/schema.prisma"],
    example:
      "postgresql://postgres.[ref]:[PASSWORD]@aws-0-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require",
    secret: true,
  },
  {
    name: "AUTH_SECRET",
    tier: "critical",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Segredo HS256 do cookie ecopet-session (JWT) — middleware Edge + APIs auth",
    usedIn: [
      "apps/web/src/lib/auth-secret.ts",
      "apps/web/src/lib/auth-session.ts",
      "apps/web/src/lib/edge/session.ts",
    ],
    example: "openssl rand -base64 32",
    secret: true,
  },
  {
    name: "NEXTAUTH_SECRET",
    tier: "critical",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Fallback de AUTH_SECRET (NextAuth) — pode ser igual a AUTH_SECRET",
    usedIn: ["apps/web/src/lib/auth-secret.ts", "apps/web/src/lib/env.ts"],
    example: "openssl rand -base64 32 (mesmo valor de AUTH_SECRET ou omitir se AUTH_SECRET definido)",
    secret: true,
  },
  {
    name: "NEXTAUTH_URL",
    tier: "critical",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "URL pública HTTPS do site — cookies, redirects, links de e-mail",
    usedIn: [
      "apps/web/src/lib/app-url.ts",
      "apps/web/src/lib/env.ts",
      "apps/web/src/lib/auth-session.ts",
    ],
    example: "https://ecopet-web.vercel.app",
  },
  {
    name: "APP_URL",
    tier: "critical",
    scopes: ["web", "api"],
    environments: ["Production", "Preview"],
    purpose: "URL base do app para links transacionais e reset de senha",
    usedIn: [
      "apps/web/src/lib/env.ts",
      "apps/web/src/lib/password-reset.ts",
      "apps/web/src/lib/mail/config.ts",
    ],
    example: "https://ecopet-web.vercel.app",
  },
  {
    name: "NEXT_PUBLIC_APP_URL",
    tier: "critical",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "URL pública exposta ao browser (metadata, sitemap, links sociais)",
    usedIn: [
      "apps/web/src/app/layout.tsx",
      "apps/web/src/app/sitemap.ts",
      "apps/web/src/lib/social/utils.ts",
    ],
    example: "https://ecopet-web.vercel.app",
  },

  // ─── Recomendadas (funcionalidades principais em produção) ───
  {
    name: "RESEND_API_KEY",
    tier: "recommended",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Envio de e-mail transacional e recuperação de senha (OTP)",
    usedIn: [
      "apps/web/src/lib/email/provider.ts",
      "apps/web/src/lib/email/email-service.ts",
      "apps/web/src/lib/email/password-recovery-email.ts",
    ],
    example: "re_xxxxxxxxxxxxxxxxxxxxxxxx",
    secret: true,
  },
  {
    name: "EMAIL_FROM",
    tier: "recommended",
    scopes: ["web", "api"],
    environments: ["Production", "Preview"],
    purpose: "Remetente verificado para e-mails (Resend/SendGrid/Brevo)",
    usedIn: [
      "apps/web/src/lib/email/config.ts",
      "apps/web/src/lib/email/provider.ts",
      "apps/web/src/lib/email/email-service.ts",
    ],
    example: "EcoPet <noreply@eccopet.com>",
  },
  {
    name: "EMAIL_PROVIDER",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Provedor de e-mail preferido (resend, smtp, …)",
    usedIn: ["apps/web/src/lib/email/config.ts", "apps/web/src/lib/email/provider.ts"],
    example: "resend",
  },
  {
    name: "EMAIL_REPLY_TO",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Reply-To opcional nos e-mails transacionais",
    usedIn: ["apps/web/src/lib/email/config.ts", "apps/web/src/lib/email/email-service.ts"],
    example: "suporte@eccopet.com",
  },
  {
    name: "EMAIL_SUPPORT",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Endereço de suporte exibido no rodapé dos e-mails",
    usedIn: ["apps/web/src/lib/email/config.ts", "apps/web/src/lib/email/templates/components/layout.ts"],
    example: "suporte@eccopet.com",
  },
  {
    name: "EMAIL_DOMAIN_VERIFIED",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Marca domínio Resend como verificado (ACTIVE no admin)",
    usedIn: ["apps/web/src/lib/email/config.ts", "apps/web/src/lib/email/resend-status.ts"],
    example: "true",
  },
  {
    name: "CLOUDINARY_CLOUD_NAME",
    tier: "recommended",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Upload de mídia em produção (assinatura server-side)",
    usedIn: [
      "apps/web/src/lib/storage/cloudinary.ts",
      "apps/web/src/app/api/uploads/cloudinary/signature/route.ts",
    ],
    example: "seu-cloud-name",
  },
  {
    name: "CLOUDINARY_API_KEY",
    tier: "recommended",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Chave pública Cloudinary para upload assinado",
    usedIn: ["apps/web/src/lib/storage/cloudinary.ts"],
    example: "123456789012345",
    secret: true,
  },
  {
    name: "CLOUDINARY_API_SECRET",
    tier: "recommended",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Segredo Cloudinary — apenas servidor, nunca expor ao client",
    usedIn: ["apps/web/src/lib/storage/cloudinary.ts"],
    example: "xxxxxxxxxxxxxxxxxxxxxxxx",
    secret: true,
  },

  // ─── API Express (apps/api — NÃO necessária na Vercel se só web deployado) ───
  {
    name: "JWT_SECRET",
    tier: "critical",
    scopes: ["api"],
    environments: ["Production", "Preview", "Development"],
    purpose: "JWT da API Express (apps/api) — não usado pelo Next.js auth principal",
    usedIn: ["apps/api/src/lib/env.ts", "apps/api/src/lib/session-tokens.ts"],
    example: "openssl rand -base64 32",
    secret: true,
  },
  {
    name: "WEB_URL",
    tier: "critical",
    scopes: ["api", "scripts"],
    environments: ["Production", "Preview", "Development"],
    purpose: "URL do frontend para CORS e links na API Express",
    usedIn: ["apps/api/src/index.ts", "apps/api/src/lib/env.ts"],
    example: "https://ecopet-web.vercel.app",
  },
  {
    name: "API_INTERNAL_URL",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Proxy Next.js → API Express (/api/ecopet/*) — opcional se tudo via Route Handlers",
    usedIn: ["apps/web/src/lib/api-url.server.ts", "apps/web/src/app/api/ecopet/[...path]/route.ts"],
    example: "http://localhost:4000",
  },
  {
    name: "NEXT_PUBLIC_API_URL",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "URL pública da API no browser (fallback do proxy)",
    usedIn: ["apps/web/src/lib/api-url.client.ts", "apps/web/src/lib/api-url.server.ts"],
    example: "https://api.seudominio.com",
  },

  // ─── E-mail alternativo ───
  {
    name: "SMTP_HOST",
    tier: "optional",
    scopes: ["web", "api"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Host SMTP alternativo ao Resend",
    usedIn: ["apps/web/src/lib/mail/config.ts", "apps/web/src/lib/integrations/env-check.ts"],
    example: "smtp.gmail.com",
  },
  {
    name: "SMTP_PORT",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Porta SMTP",
    usedIn: ["apps/web/src/lib/mail/config.ts", "apps/web/src/lib/env.ts"],
    example: "587",
  },
  {
    name: "SMTP_USER",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Usuário SMTP",
    usedIn: ["apps/web/src/lib/mail/config.ts"],
    example: "no-reply@seudominio.com",
    secret: true,
  },
  {
    name: "SMTP_PASS",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Senha SMTP / app password",
    usedIn: ["apps/web/src/lib/mail/config.ts"],
    example: "senha-de-app",
    secret: true,
  },
  {
    name: "SMTP_PASSWORD",
    tier: "optional",
    scopes: ["web"],
    environments: ["Development"],
    purpose: "Alias legado de SMTP_PASS",
    usedIn: ["apps/web/src/lib/integrations/env-check.ts"],
    example: "senha-de-app",
    secret: true,
    legacy: true,
  },
  {
    name: "SMTP_SECURE",
    tier: "optional",
    scopes: ["web", "scripts"],
    environments: ["Development"],
    purpose: "Força TLS direto (porta 465)",
    usedIn: ["apps/web/src/lib/mail/config.ts"],
    example: "false",
  },
  {
    name: "SMTP_FROM_NAME",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Nome exibido do remetente",
    usedIn: ["apps/web/src/lib/mail/config.ts", "apps/web/src/lib/email/provider.ts"],
    example: "EcoPet",
  },
  {
    name: "SMTP_FROM_EMAIL",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "E-mail do remetente SMTP",
    usedIn: ["apps/web/src/lib/mail/config.ts", "apps/web/src/lib/email/provider.ts"],
    example: "no-reply@seudominio.com",
  },
  {
    name: "SMTP_FROM",
    tier: "optional",
    scopes: ["web", "api", "scripts"],
    environments: ["Development"],
    purpose: "Remetente legado (formato livre)",
    usedIn: ["apps/web/src/lib/mail/config.ts", "apps/api/src/services/email-providers.ts"],
    example: "EcoPet <no-reply@seudominio.com>",
    legacy: true,
  },
  {
    name: "MAIL_PROVIDER",
    tier: "optional",
    scopes: ["web", "scripts"],
    environments: ["Development"],
    purpose: "Preset SMTP (gmail, outlook, custom)",
    usedIn: ["apps/web/src/lib/mail/config.ts"],
    example: "gmail",
  },
  {
    name: "SENDGRID_API_KEY",
    tier: "optional",
    scopes: ["web", "api"],
    environments: ["Production", "Preview"],
    purpose: "Provedor alternativo de e-mail",
    usedIn: ["apps/web/src/lib/email/provider.ts"],
    example: "SG.xxxxx",
    secret: true,
  },
  {
    name: "BREVO_API_KEY",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Provedor alternativo de e-mail (Brevo)",
    usedIn: ["apps/web/src/lib/email/provider.ts"],
    example: "xkeysib-xxxxx",
    secret: true,
  },
  {
    name: "RESEND_FROM",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Alias de remetente Resend",
    usedIn: ["apps/web/src/lib/email/provider.ts"],
    example: "onboarding@resend.dev",
    legacy: true,
  },

  // ─── Upload / Supabase storage ───
  {
    name: "UPLOAD_PROVIDER",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Provedor de upload (cloudinary, …)",
    usedIn: ["apps/web/src/lib/upload/service.ts", "apps/web/src/lib/integrations/env-check.ts"],
    example: "cloudinary",
  },
  {
    name: "UPLOAD_DEV_FALLBACK",
    tier: "optional",
    scopes: ["web"],
    environments: ["Development"],
    purpose: "Permite upload local em dev sem Cloudinary",
    usedIn: ["apps/web/src/lib/integrations/env-check.ts", "apps/web/src/lib/upload/service.ts"],
    example: "1",
  },
  {
    name: "SUPABASE_URL",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Storage Supabase (alternativa ao Cloudinary — ainda não implementado)",
    usedIn: ["apps/web/src/lib/integrations/env-check.ts"],
    example: "https://xxxxx.supabase.co",
  },
  {
    name: "SUPABASE_SERVICE_ROLE_KEY",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Chave service role Supabase Storage",
    usedIn: ["apps/web/src/lib/integrations/env-check.ts"],
    example: "eyJhbGci...",
    secret: true,
  },
  {
    name: "SUPABASE_STORAGE_BUCKET",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Bucket Supabase Storage",
    usedIn: ["apps/web/src/lib/integrations/env-check.ts"],
    example: "ecopet-uploads",
  },

  // ─── SMS / recuperação por telefone ───
  {
    name: "SMS_PROVIDER",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Provedor SMS (twilio, zenvia, infobip)",
    usedIn: ["apps/web/src/lib/sms/provider.ts", "apps/web/src/lib/sms/twilio.ts"],
    example: "twilio",
  },
  {
    name: "TWILIO_ACCOUNT_SID",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Conta Twilio para SMS",
    usedIn: ["apps/web/src/lib/sms/twilio.ts"],
    example: "ACxxxxxxxx",
    secret: true,
  },
  {
    name: "TWILIO_AUTH_TOKEN",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Token Twilio",
    usedIn: ["apps/web/src/lib/sms/twilio.ts"],
    example: "xxxxxxxx",
    secret: true,
  },
  {
    name: "TWILIO_PHONE_NUMBER",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Número remetente Twilio",
    usedIn: ["apps/web/src/lib/sms/twilio.ts"],
    example: "+5511999999999",
  },
  {
    name: "PHONE_SMS_RECOVERY_ENABLED",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Habilita/desabilita recuperação por SMS",
    usedIn: ["apps/web/src/lib/auth/recovery-identifier.ts"],
    example: "1",
  },
  {
    name: "ZENVIA_API_TOKEN",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Token Zenvia SMS",
    usedIn: ["apps/web/src/lib/sms/provider.ts"],
    example: "xxxxx",
    secret: true,
  },
  {
    name: "INFOBIP_API_KEY",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "API key Infobip SMS",
    usedIn: ["apps/web/src/lib/sms/provider.ts"],
    example: "xxxxx",
    secret: true,
  },
  {
    name: "INFOBIP_BASE_URL",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Base URL Infobip",
    usedIn: ["apps/web/src/lib/sms/provider.ts"],
    example: "https://api.infobip.com",
  },
  {
    name: "SMS_API_KEY",
    tier: "optional",
    scopes: ["web"],
    environments: ["Development"],
    purpose: "Chave genérica SMS",
    usedIn: ["apps/web/src/lib/sms/provider.ts"],
    legacy: true,
    example: "xxxxx",
    secret: true,
  },
  {
    name: "SMS_SENDER",
    tier: "optional",
    scopes: ["web"],
    environments: ["Development"],
    purpose: "Nome remetente SMS",
    usedIn: ["apps/web/src/lib/sms/provider.ts"],
    example: "EcoPet",
  },

  // ─── TalkJS ───
  {
    name: "NEXT_PUBLIC_TALKJS_APP_ID",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "App ID TalkJS (chat) — exposto ao browser",
    usedIn: [
      "apps/web/src/lib/talkjs/client.ts",
      "apps/web/src/components/messages/TalkJSSessionProvider.tsx",
    ],
    example: "tXXXXXX",
  },
  {
    name: "TALKJS_SECRET_KEY",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Segredo servidor TalkJS",
    usedIn: ["apps/web/src/lib/talkjs/server.ts", "apps/web/src/app/api/webhooks/talkjs/route.ts"],
    example: "sk_xxxxx",
    secret: true,
  },
  {
    name: "TALKJS_WEBHOOK_VERIFY",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production"],
    purpose: "Exige assinatura em webhooks TalkJS",
    usedIn: ["apps/web/src/app/api/webhooks/talkjs/route.ts"],
    example: "1",
  },

  // ─── IA ───
  {
    name: "OPENAI_API_KEY",
    tier: "optional",
    scopes: ["web", "api"],
    environments: ["Production", "Preview"],
    purpose: "OpenAI — assistente, moderação, tradução",
    usedIn: ["apps/web/src/lib/ai/openai-client.ts", "apps/api/src/services/ai-chat-service.ts"],
    example: "sk-xxxxx",
    secret: true,
  },
  {
    name: "OPENAI_MODEL",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Modelo OpenAI no web",
    usedIn: ["apps/web/src/lib/ai/ai-config.ts"],
    example: "gpt-4o-mini",
  },
  {
    name: "OPENAI_EMBEDDING_MODEL",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Modelo de embeddings OpenAI",
    usedIn: ["apps/web/src/lib/ai/ai-config.ts"],
    example: "text-embedding-3-small",
  },
  {
    name: "OPENAI_MODERATION_MODEL",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Modelo de moderação OpenAI",
    usedIn: ["apps/web/src/lib/ai/ai-config.ts"],
    example: "omni-moderation-latest",
  },
  {
    name: "OPENAI_MAX_OUTPUT_TOKENS",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Limite de tokens de saída",
    usedIn: ["apps/web/src/lib/ai/ai-config.ts"],
    example: "1024",
  },
  {
    name: "OPENAI_REQUEST_TIMEOUT_MS",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Timeout das chamadas OpenAI",
    usedIn: ["apps/web/src/lib/ai/openai-client.ts"],
    example: "30000",
  },
  {
    name: "OPENAI_DAILY_USER_LIMIT",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Limite diário de requisições IA por usuário",
    usedIn: ["apps/web/src/lib/ai/ai-rate-limit.ts"],
    example: "50",
  },
  {
    name: "OPENAI_MONTHLY_BUDGET_CENTS",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Teto mensal de custo estimado da IA (centavos USD)",
    usedIn: ["apps/web/src/lib/ai/ai-rate-limit.ts"],
    example: "500",
  },
  {
    name: "AI_ENABLED",
    tier: "optional",
    scopes: ["api", "web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Flag global de IA",
    usedIn: ["apps/api/src/lib/ai-config.ts", "apps/web/src/lib/ai/ai-config.ts"],
    example: "false",
  },
  {
    name: "AI_MODEL",
    tier: "optional",
    scopes: ["api"],
    environments: ["Production", "Preview"],
    purpose: "Modelo OpenAI na API",
    usedIn: ["apps/api/src/services/ai-chat-service.ts"],
    example: "gpt-4o-mini",
  },
  {
    name: "SUPPORT_AI_ENABLED",
    tier: "optional",
    scopes: ["api"],
    environments: ["Production", "Preview"],
    purpose: "IA no chat de suporte",
    usedIn: ["apps/api/src/services/ai-chat-service.ts"],
    example: "true",
  },
  {
    name: "SOCIAL_AI_MODERATION_API_KEY",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Moderação externa de posts",
    usedIn: ["apps/web/src/lib/social/moderation/external-ai-moderation.ts"],
    example: "xxxxx",
    secret: true,
  },
  {
    name: "CPF_LOOKUP_ENABLED",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Habilita consulta CPF externa",
    usedIn: ["apps/web/src/lib/integrations/cpf/cpf-service.ts"],
    example: "1",
  },

  // ─── Pagamentos ───
  {
    name: "PAYMENT_PROVIDER",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Provedor preferido: MERCADO_PAGO | PAGARME | STRIPE",
    usedIn: ["apps/web/src/lib/integrations/env-check.ts"],
    example: "MERCADO_PAGO",
  },
  {
    name: "MERCADO_PAGO_ACCESS_TOKEN",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Token Mercado Pago",
    usedIn: ["apps/web/src/lib/integrations/env-check.ts", "apps/web/src/lib/payments/providers/index.ts"],
    example: "APP_USR-xxxxx",
    secret: true,
  },
  {
    name: "NEXT_PUBLIC_MERCADO_PAGO_PUBLIC_KEY",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Public Key Mercado Pago (Checkout Transparente — browser)",
    usedIn: ["apps/web/src/lib/mercado-pago/config.ts"],
    example: "TEST-xxxxx",
  },
  {
    name: "MERCADO_PAGO_PUBLIC_KEY",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Alias server-side da Public Key (preferir NEXT_PUBLIC_*)",
    usedIn: ["apps/web/src/lib/mercado-pago/config.ts"],
    example: "TEST-xxxxx",
    legacy: true,
  },
  {
    name: "MERCADO_PAGO_ENVIRONMENT",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "test | production — default seguro: test",
    usedIn: ["apps/web/src/lib/mercado-pago/config.ts"],
    example: "test",
  },
  {
    name: "MERCADOPAGO_ACCESS_TOKEN",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Alias legado (sem underscore) usado no gestor",
    usedIn: ["apps/web/src/lib/gestor/gestor-support-service.ts"],
    example: "APP_USR-xxxxx",
    secret: true,
    legacy: true,
  },
  {
    name: "MERCADO_PAGO_WEBHOOK_SECRET",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production"],
    purpose: "Validação de webhooks Mercado Pago",
    usedIn: ["docs/integrations"],
    example: "xxxxx",
    secret: true,
    legacy: true,
  },
  {
    name: "NEXT_PUBLIC_TURNSTILE_SITE_KEY",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Cloudflare Turnstile Site Key (pública)",
    usedIn: ["apps/web/src/lib/turnstile", "docs/cloudflare-turnstile.md"],
    example: "0x4AAAAAAA...",
    secret: false,
  },
  {
    name: "TURNSTILE_SECRET_KEY",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Cloudflare Turnstile Secret Key (somente servidor)",
    usedIn: ["apps/web/src/lib/turnstile", "docs/cloudflare-turnstile.md"],
    example: "0x4AAAAAAA...",
    secret: true,
  },
  {
    name: "TURNSTILE_ENABLED",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Ativa/desativa Turnstile (false = skip controlado)",
    usedIn: ["apps/web/src/lib/turnstile/config.ts"],
    example: "true",
    secret: false,
  },
  {
    name: "TURNSTILE_ALLOWED_HOSTNAMES",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Hostnames permitidos na validação siteverify (CSV)",
    usedIn: ["apps/web/src/lib/turnstile/hostname.ts"],
    example: "eccopet.com,www.eccopet.com",
    secret: false,
  },
  {
    name: "TURNSTILE_TIMEOUT_MS",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Timeout da chamada siteverify (ms)",
    usedIn: ["apps/web/src/lib/turnstile/config.ts"],
    example: "5000",
    secret: false,
  },
  {
    name: "PAGARME_API_KEY",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "API key Pagar.me",
    usedIn: ["apps/web/src/lib/integrations/env-check.ts"],
    example: "sk_xxxxx",
    secret: true,
  },
  {
    name: "STRIPE_SECRET_KEY",
    tier: "optional",
    scopes: ["web", "api"],
    environments: ["Production", "Preview"],
    purpose: "Chave secreta Stripe",
    usedIn: ["apps/web/src/lib/integrations/env-check.ts"],
    example: "sk_live_xxxxx",
    secret: true,
  },
  {
    name: "STRIPE_PUBLISHABLE_KEY",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Chave pública Stripe (legado; preferir NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY)",
    usedIn: ["apps/web/src/lib/integrations/env-check.ts"],
    example: "pk_live_xxxxx",
    legacy: true,
  },
  {
    name: "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Chave pública Stripe exposta ao browser",
    usedIn: ["apps/web/src/lib/integrations/env-check.ts"],
    example: "pk_live_xxxxx",
  },
  {
    name: "STRIPE_WEBHOOK_SECRET",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production"],
    purpose: "Segredo de validação de webhooks Stripe",
    usedIn: ["apps/web/src/lib/integrations/env-check.ts"],
    example: "whsec_xxxxx",
    secret: true,
  },

  // ─── Push (Web Push / VAPID) ───
  {
    name: "NEXT_PUBLIC_VAPID_PUBLIC_KEY",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Chave pública VAPID para Web Push",
    usedIn: ["apps/web/src/lib/integrations/env-check.ts"],
    example: "BNxxxxx",
  },
  {
    name: "VAPID_PRIVATE_KEY",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Chave privada VAPID (somente servidor)",
    usedIn: ["apps/web/src/lib/integrations/env-check.ts"],
    example: "xxxxx",
    secret: true,
  },
  {
    name: "VAPID_SUBJECT",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "mailto: ou URL do contato VAPID",
    usedIn: ["apps/web/src/lib/integrations/env-check.ts"],
    example: "mailto:admin@seudominio.com",
  },

  // ─── Firebase Cloud Messaging (Web) ───
  {
    name: "NEXT_PUBLIC_FIREBASE_API_KEY",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Firebase Web API Key (pública) para FCM no cliente",
    usedIn: ["apps/web/src/lib/firebase/config.ts"],
    example: "AIza...",
    secret: false,
  },
  {
    name: "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Domínio Auth do projeto Firebase (config Web SDK)",
    usedIn: ["apps/web/src/lib/firebase/config.ts"],
    example: "seu-projeto.firebaseapp.com",
  },
  {
    name: "NEXT_PUBLIC_FIREBASE_PROJECT_ID",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Project ID Firebase (cliente)",
    usedIn: ["apps/web/src/lib/firebase/config.ts"],
    example: "seu-projeto",
  },
  {
    name: "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Storage bucket Firebase (config Web SDK)",
    usedIn: ["apps/web/src/lib/firebase/config.ts"],
    example: "seu-projeto.appspot.com",
  },
  {
    name: "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Sender ID FCM (cliente)",
    usedIn: ["apps/web/src/lib/firebase/config.ts"],
    example: "123456789012",
  },
  {
    name: "NEXT_PUBLIC_FIREBASE_APP_ID",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "App ID Firebase Web",
    usedIn: ["apps/web/src/lib/firebase/config.ts"],
    example: "1:123:web:abc",
  },
  {
    name: "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Measurement ID Analytics (opcional)",
    usedIn: ["apps/web/src/lib/firebase/config.ts"],
    example: "G-XXXX",
  },
  {
    name: "NEXT_PUBLIC_FIREBASE_VAPID_KEY",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Chave VAPID pública do Firebase Cloud Messaging (Web Push certificates)",
    usedIn: ["apps/web/src/lib/firebase/config.ts", "apps/web/src/lib/firebase/messaging-client.ts"],
    example: "BNxxxxx",
  },
  {
    name: "FIREBASE_PROJECT_ID",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Project ID para Firebase Admin SDK (FCM HTTP v1)",
    usedIn: ["apps/web/src/lib/firebase/admin.ts"],
    example: "seu-projeto",
  },
  {
    name: "FIREBASE_CLIENT_EMAIL",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "E-mail da service account Firebase Admin",
    usedIn: ["apps/web/src/lib/firebase/admin.ts"],
    example: "firebase-adminsdk-...@seu-projeto.iam.gserviceaccount.com",
    secret: true,
  },
  {
    name: "FIREBASE_PRIVATE_KEY",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Private key da service account (com \\n) — somente servidor",
    usedIn: ["apps/web/src/lib/firebase/admin.ts"],
    example: "-----BEGIN PRIVATE KEY-----\\n...\\n-----END PRIVATE KEY-----\\n",
    secret: true,
  },
  {
    name: "FIREBASE_MESSAGING_ENABLED",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Flag opcional para desabilitar FCM sem remover variáveis",
    usedIn: ["apps/web/src/lib/firebase/admin.ts"],
    example: "true",
  },

  // ─── Build ───
  {
    name: "NODE_OPTIONS",
    tier: "optional",
    scopes: ["web", "scripts"],
    environments: ["Development", "CI"],
    purpose: "Flags Node (ex.: heap maior no build local)",
    usedIn: ["package.json", "scripts/sync-web-env.mjs"],
    example: "--max-old-space-size=8192",
  },

  // ─── Mapas / logística ───
  {
    name: "GOOGLE_MAPS_API_KEY",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Google Maps",
    usedIn: ["apps/web/src/lib/integrations/env-check.ts"],
    example: "AIzaSyxxxxx",
    secret: true,
  },
  {
    name: "MAPBOX_ACCESS_TOKEN",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Mapbox",
    usedIn: ["apps/web/src/lib/integrations/env-check.ts"],
    example: "pk.xx",
    secret: true,
  },
  {
    name: "MELHOR_ENVIO_TOKEN",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Frete Melhor Envio",
    usedIn: ["apps/web/src/lib/integrations/env-check.ts"],
    example: "xxxxx",
    secret: true,
  },
  {
    name: "WHATSAPP_API_TOKEN",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "WhatsApp Business API",
    usedIn: ["apps/web/src/lib/integrations/env-check.ts"],
    example: "xxxxx",
    secret: true,
  },
  {
    name: "WHATSAPP_PHONE_NUMBER_ID",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "ID do número WhatsApp Business",
    usedIn: ["apps/web/src/lib/integrations/env-check.ts"],
    example: "1234567890",
  },
  {
    name: "WHATSAPP_BUSINESS_TOKEN",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Token notificações WhatsApp",
    usedIn: ["apps/web/src/lib/notifications/channels/whatsapp.ts"],
    example: "xxxxx",
    secret: true,
  },

  // ─── Observabilidade ───
  {
    name: "SENTRY_DSN",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Sentry server-side",
    usedIn: ["apps/web/src/lib/observability/error-reporter.ts"],
    example: "https://xxxxx@o0.ingest.sentry.io/0",
    secret: true,
  },
  {
    name: "NEXT_PUBLIC_SENTRY_DSN",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Sentry client-side",
    usedIn: ["apps/web/src/lib/gestor/integrations/future-bi.ts"],
    example: "https://xxxxx@o0.ingest.sentry.io/0",
  },
  {
    name: "NEXT_PUBLIC_GA_MEASUREMENT_ID",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production"],
    purpose: "Google Analytics",
    usedIn: ["apps/web/src/lib/gestor/integrations/future-bi.ts"],
    example: "G-XXXXXXXX",
  },
  {
    name: "NEXT_PUBLIC_POSTHOG_KEY",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "PostHog analytics",
    usedIn: ["apps/web/src/lib/observability/providers.ts"],
    example: "phc_xxxxx",
  },
  {
    name: "NEXT_PUBLIC_POSTHOG_HOST",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Host PostHog",
    usedIn: ["docs"],
    example: "https://app.posthog.com",
  },
  {
    name: "LOGTAIL_SOURCE_TOKEN",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production"],
    purpose: "Logtail",
    usedIn: ["apps/web/src/lib/observability/providers.ts"],
    example: "xxxxx",
    secret: true,
  },
  {
    name: "DD_API_KEY",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production"],
    purpose: "Datadog",
    usedIn: ["apps/web/src/lib/observability/providers.ts"],
    example: "xxxxx",
    secret: true,
  },
  {
    name: "NEXT_PUBLIC_VERCEL_ANALYTICS_ID",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production"],
    purpose: "Vercel Analytics",
    usedIn: ["apps/web/src/lib/observability/providers.ts"],
    example: "auto",
  },

  // ─── API Express extras ───
  {
    name: "JWT_ACCESS_EXPIRY",
    tier: "optional",
    scopes: ["api"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Expiração access token API",
    usedIn: ["apps/api/src/lib/session-tokens.ts"],
    example: "15m",
  },
  {
    name: "JWT_REFRESH_DAYS",
    tier: "optional",
    scopes: ["api"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Dias do refresh token API",
    usedIn: ["apps/api/src/lib/session-tokens.ts"],
    example: "7",
  },
  {
    name: "API_PORT",
    tier: "optional",
    scopes: ["api", "scripts"],
    environments: ["Development"],
    purpose: "Porta local da API Express",
    usedIn: ["apps/api/src/index.ts"],
    example: "4000",
  },
  {
    name: "PORT",
    tier: "optional",
    scopes: ["api"],
    environments: ["Production", "Preview"],
    purpose: "Porta injetada pelo host (Heroku/Railway)",
    usedIn: ["apps/api/src/index.ts"],
    platform: "vercel",
    example: "4000",
  },
  {
    name: "DEEPL_API_KEY",
    tier: "optional",
    scopes: ["api"],
    environments: ["Production", "Preview"],
    purpose: "Tradução DeepL",
    usedIn: ["apps/api/src/services/translation-service.ts"],
    example: "xxxxx",
    secret: true,
  },
  {
    name: "GOOGLE_TRANSLATE_API_KEY",
    tier: "optional",
    scopes: ["api"],
    environments: ["Production", "Preview"],
    purpose: "Tradução Google",
    usedIn: ["apps/api/src/services/translation-service.ts"],
    example: "AIzaSyxxxxx",
    secret: true,
  },

  // ─── Dev / testes / debug ───
  {
    name: "NODE_ENV",
    tier: "optional",
    scopes: ["web", "api", "database"],
    environments: ["Production", "Preview", "Development"],
    purpose: "Ambiente Node (development | production | test)",
    usedIn: ["Vários módulos"],
    example: "production",
    platform: "vercel",
  },
  {
    name: "VERCEL",
    tier: "optional",
    scopes: ["web", "database"],
    environments: ["Production", "Preview"],
    purpose: "Flag de deploy Vercel — injetada automaticamente",
    usedIn: ["apps/web/src/lib/app-url.ts", "packages/database/src/client.ts"],
    platform: "vercel",
    example: "1",
  },
  {
    name: "VERCEL_URL",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production", "Preview"],
    purpose: "Hostname do deploy atual — fallback de URL pública",
    usedIn: ["apps/web/src/lib/app-url.ts"],
    platform: "vercel",
    example: "ecopet-web-xxx.vercel.app",
  },
  {
    name: "VERCEL_PROJECT_PRODUCTION_URL",
    tier: "optional",
    scopes: ["web"],
    environments: ["Production"],
    purpose: "URL de produção do projeto Vercel",
    usedIn: ["apps/web/src/lib/app-url.ts"],
    platform: "vercel",
    example: "ecopet-web.vercel.app",
  },
  {
    name: "FORCE_INSECURE_SESSION_COOKIE",
    tier: "optional",
    scopes: ["web"],
    environments: ["Development"],
    purpose: "Desativa cookie Secure (debug local HTTP)",
    usedIn: ["apps/web/src/lib/auth-session.ts"],
    example: "1",
  },
  {
    name: "AUTH_RATE_LIMIT_RELAXED",
    tier: "optional",
    scopes: ["web"],
    environments: ["Development"],
    purpose: "Afrouxa rate limit de auth em testes (limite alto, ainda ativo)",
    usedIn: ["apps/web/src/lib/rate-limit.ts"],
    example: "1",
  },
  {
    name: "AUTH_RATE_LIMIT_DISABLED",
    tier: "optional",
    scopes: ["web"],
    environments: ["Development"],
    purpose: "Desliga rate limit de auth (somente suites locais; nunca em produção)",
    usedIn: ["apps/web/src/lib/rate-limit.ts"],
    example: "1",
  },
  {
    name: "AUTH_TEST_RESET_RATE_LIMIT",
    tier: "optional",
    scopes: ["web", "scripts"],
    environments: ["Development"],
    purpose: "Habilita POST /api/auth/test/reset-rate-limit para limpar buckets in-memory",
    usedIn: ["apps/web/src/app/api/auth/test/reset-rate-limit/route.ts"],
    example: "1",
  },
  {
    name: "RATE_LIMIT_FORCE",
    tier: "optional",
    scopes: ["web"],
    environments: ["Development"],
    purpose: "Força rate limit em dev",
    usedIn: ["apps/web/src/lib/rate-limit.ts"],
    example: "1",
  },
  {
    name: "AUTH_TEST_EXPOSE_OTP",
    tier: "optional",
    scopes: ["web", "scripts"],
    environments: ["Development"],
    purpose: "Expõe OTP em respostas de teste",
    usedIn: ["apps/web/src/lib/auth/recovery-otp-dev.ts"],
    example: "1",
  },
  {
    name: "AUTH_TEST_OTP_TTL_MS",
    tier: "optional",
    scopes: ["web", "scripts"],
    environments: ["Development"],
    purpose: "TTL curto de OTP para testes",
    usedIn: ["apps/web/src/lib/auth/verification-code.ts"],
    example: "500",
  },
  {
    name: "ALLOW_TEST_RESEND",
    tier: "optional",
    scopes: ["web"],
    environments: ["Development"],
    purpose: "Permite rotas /api/test-resend em produção",
    usedIn: ["apps/web/src/app/api/test-resend/route.ts"],
    example: "1",
  },
  {
    name: "ECOPET_PROXY_LOG",
    tier: "optional",
    scopes: ["web"],
    environments: ["Development"],
    purpose: "Logs do proxy /api/ecopet",
    usedIn: ["apps/web/src/app/api/ecopet/[...path]/route.ts"],
    example: "1",
  },
  {
    name: "ECOPET_BOOTSTRAP_ADMIN_EMAIL",
    tier: "optional",
    scopes: ["scripts"],
    environments: ["CI", "Development"],
    purpose: "E-mail do primeiro admin (npm run admin:bootstrap)",
    usedIn: ["scripts/admin-bootstrap.mjs"],
    example: "admin@seudominio.com",
  },
  {
    name: "ECOPET_BOOTSTRAP_ADMIN_PASSWORD",
    tier: "optional",
    scopes: ["scripts"],
    environments: ["CI", "Development"],
    purpose: "Senha do primeiro admin",
    usedIn: ["scripts/admin-bootstrap.mjs"],
    example: "SenhaForte@2026",
    secret: true,
  },
  {
    name: "TEST_EMAIL",
    tier: "optional",
    scopes: ["scripts"],
    environments: ["Development"],
    purpose: "Destinatário para npm run test:mail",
    usedIn: ["scripts/test-mail.mjs"],
    example: "voce@email.com",
  },
  {
    name: "WEB_URL",
    tier: "optional",
    scopes: ["scripts"],
    environments: ["Development", "CI"],
    purpose: "URL base para scripts de teste HTTP",
    usedIn: ["scripts/test-foundation-auth.mjs", "playwright.config.ts"],
    example: "http://localhost:3000",
  },
  {
    name: "API_URL",
    tier: "optional",
    scopes: ["scripts"],
    environments: ["Development"],
    purpose: "URL da API para scripts de teste",
    usedIn: ["scripts/test-auth.mjs"],
    example: "http://localhost:4000",
  },
];

export function getRegistryByTier(tier: EnvTier): EnvVarDefinition[] {
  return ENV_REGISTRY.filter((v) => v.tier === tier);
}

export function getRegistryForScope(scope: EnvScope): EnvVarDefinition[] {
  return ENV_REGISTRY.filter((v) => v.scopes.includes(scope));
}
