import { brl, fixedSku, item } from "./catalog-helpers";
import { SOURCE_DOCUMENT, type CatalogItem } from "./types";

const PRT_SECTION = "12. Saúde, planos, seguros e assistências";
const IOT_SECTION = "13. IoT, dispositivos, APIs e enterprise";

export const PROTECT_CATALOG: CatalogItem[] = [
  item({
    sku: "PRT-001",
    name: "Clube preventivo",
    suite: "PROTECT",
    kind: "PROTECT",
    pricingMode: "PARTNER_PRODUCT",
    commercialAvailability: "DISABLED",
    revenueRecognition: "PREMIUM_NOT_REVENUE",
    amountCents: brl(29.9),
    eccopetRevenueRefCents: brl(8.97),
    costReferenceCents: brl(8),
    portfolioSuiteId: "protect",
    sourceDocument: SOURCE_DOCUMENT,
    sourceSection: PRT_SECTION,
    sourceSku: "PRT-001",
  }),
  item({
    sku: "PRT-002",
    name: "Plano ambulatorial parceiro",
    suite: "PROTECT",
    kind: "PROTECT",
    pricingMode: "PARTNER_PRODUCT",
    commercialAvailability: "PARTNER_REQUIRED",
    revenueRecognition: "PREMIUM_NOT_REVENUE",
    amountCents: brl(59.9),
    eccopetRevenueRefCents: brl(11.98),
    costReferenceCents: brl(12),
    portfolioSuiteId: "protect",
    sourceDocument: SOURCE_DOCUMENT,
    sourceSection: PRT_SECTION,
    sourceSku: "PRT-002",
  }),
  item({
    sku: "PRT-003",
    name: "Plano completo parceiro",
    suite: "PROTECT",
    kind: "PROTECT",
    pricingMode: "PARTNER_PRODUCT",
    commercialAvailability: "PARTNER_REQUIRED",
    revenueRecognition: "PREMIUM_NOT_REVENUE",
    amountCents: brl(119.9),
    eccopetRevenueRefCents: brl(23.98),
    costReferenceCents: brl(22),
    portfolioSuiteId: "protect",
    sourceDocument: SOURCE_DOCUMENT,
    sourceSection: PRT_SECTION,
    sourceSku: "PRT-003",
  }),
  item({
    sku: "PRT-004",
    name: "Seguro saúde pet",
    suite: "PROTECT",
    kind: "PROTECT",
    pricingMode: "PARTNER_PRODUCT",
    commercialAvailability: "PARTNER_REQUIRED",
    revenueRecognition: "PREMIUM_NOT_REVENUE",
    amountCents: brl(69.9),
    eccopetRevenueRefCents: brl(10.49),
    costReferenceCents: brl(10),
    portfolioSuiteId: "protect",
    sourceDocument: SOURCE_DOCUMENT,
    sourceSection: PRT_SECTION,
    sourceSku: "PRT-004",
  }),
  item({
    sku: "PRT-005",
    name: "Seguro de vida do tutor + cuidado pet",
    suite: "PROTECT",
    kind: "PROTECT",
    pricingMode: "PARTNER_PRODUCT",
    commercialAvailability: "PARTNER_REQUIRED",
    revenueRecognition: "PREMIUM_NOT_REVENUE",
    amountCents: brl(29.9),
    eccopetRevenueRefCents: brl(5.98),
    costReferenceCents: brl(5.5),
    portfolioSuiteId: "protect",
    sourceDocument: SOURCE_DOCUMENT,
    sourceSection: PRT_SECTION,
    sourceSku: "PRT-005",
  }),
  item({
    sku: "PRT-006",
    name: "Assistência emergencial",
    suite: "PROTECT",
    kind: "PROTECT",
    pricingMode: "PARTNER_PRODUCT",
    commercialAvailability: "DISABLED",
    revenueRecognition: "PREMIUM_NOT_REVENUE",
    amountCents: brl(24.9),
    eccopetRevenueRefCents: brl(4.98),
    costReferenceCents: brl(7),
    portfolioSuiteId: "protect",
    sourceDocument: SOURCE_DOCUMENT,
    sourceSection: PRT_SECTION,
    sourceSku: "PRT-006",
  }),
  item({
    sku: "PRT-007",
    name: "Proteção de viagem",
    suite: "PROTECT",
    kind: "PROTECT",
    pricingMode: "PARTNER_PRODUCT",
    commercialAvailability: "DISABLED",
    revenueRecognition: "PREMIUM_NOT_REVENUE",
    amountCents: brl(39.9),
    eccopetRevenueRefCents: brl(7.98),
    costReferenceCents: brl(10),
    portfolioSuiteId: "protect",
    sourceDocument: SOURCE_DOCUMENT,
    sourceSection: PRT_SECTION,
    sourceSku: "PRT-007",
  }),
  item({
    sku: "PRT-008",
    name: "Proteção do parceiro",
    suite: "PROTECT",
    kind: "PROTECT",
    pricingMode: "PARTNER_PRODUCT",
    commercialAvailability: "PARTNER_REQUIRED",
    revenueRecognition: "PREMIUM_NOT_REVENUE",
    amountCents: brl(89.9),
    eccopetRevenueRefCents: brl(17.98),
    costReferenceCents: brl(15),
    portfolioSuiteId: "protect",
    sourceDocument: SOURCE_DOCUMENT,
    sourceSection: PRT_SECTION,
    sourceSku: "PRT-008",
  }),
  item({
    sku: "PRT-009",
    name: "Seguro cyber parceiro",
    suite: "PROTECT",
    kind: "PROTECT",
    pricingMode: "PARTNER_PRODUCT",
    commercialAvailability: "PARTNER_REQUIRED",
    revenueRecognition: "PREMIUM_NOT_REVENUE",
    amountCents: brl(69.9),
    eccopetRevenueRefCents: brl(13.98),
    costReferenceCents: brl(12),
    portfolioSuiteId: "protect",
    sourceDocument: SOURCE_DOCUMENT,
    sourceSection: PRT_SECTION,
    sourceSku: "PRT-009",
  }),
  item({
    sku: "PRT-010",
    name: "Interrupção de negócio",
    suite: "PROTECT",
    kind: "PROTECT",
    pricingMode: "PARTNER_PRODUCT",
    commercialAvailability: "PARTNER_REQUIRED",
    revenueRecognition: "PREMIUM_NOT_REVENUE",
    amountCents: brl(79.9),
    eccopetRevenueRefCents: brl(15.98),
    costReferenceCents: brl(13),
    portfolioSuiteId: "protect",
    sourceDocument: SOURCE_DOCUMENT,
    sourceSection: PRT_SECTION,
    sourceSku: "PRT-010",
  }),
];

function iotAffiliate(sku: string, name: string, price: number, revenue: number, cost: number): CatalogItem {
  return item({
    sku,
    name,
    suite: "CONNECT",
    kind: "IOT",
    pricingMode: "PARTNER_PRODUCT",
    commercialAvailability: "FEATURE_FLAGGED",
    revenueRecognition: "AFFILIATE_COMMISSION",
    amountCents: brl(price),
    eccopetRevenueRefCents: brl(revenue),
    costReferenceCents: brl(cost),
    portfolioSuiteId: "connect",
    sourceDocument: SOURCE_DOCUMENT,
    sourceSection: IOT_SECTION,
    sourceSku: sku,
  });
}

export const IOT_CATALOG: CatalogItem[] = [
  iotAffiliate("IOT-001", "Coleira GPS", 449.9, 53.99, 5),
  fixedSku({
    sku: "IOT-002",
    name: "Assinatura GPS",
    suite: "CONNECT",
    kind: "IOT",
    amountCents: brl(29.9),
    billingCycle: "month",
    costReferenceCents: brl(10),
    commercialAvailability: "FEATURE_FLAGGED",
    revenueRecognition: "SUBSCRIPTION",
    portfolioSuiteId: "connect",
    sourceSection: IOT_SECTION,
  }),
  iotAffiliate("IOT-003", "Monitor de saúde", 699.9, 83.99, 5),
  fixedSku({
    sku: "IOT-004",
    name: "Assinatura dados de saúde",
    suite: "CONNECT",
    kind: "IOT",
    amountCents: brl(44.9),
    billingCycle: "month",
    costReferenceCents: brl(15),
    commercialAvailability: "FEATURE_FLAGGED",
    revenueRecognition: "SUBSCRIPTION",
    portfolioSuiteId: "connect",
    sourceSection: IOT_SECTION,
  }),
  iotAffiliate("IOT-005", "Câmera pet", 349.9, 41.99, 5),
  iotAffiliate("IOT-006", "Armazenamento câmera", 19.9, 2.39, 5),
  iotAffiliate("IOT-007", "Comedouro inteligente", 499.9, 59.99, 5),
  iotAffiliate("IOT-008", "Bebedouro inteligente", 299.9, 35.99, 5),
  iotAffiliate("IOT-009", "Balança inteligente", 249.9, 29.99, 5),
  fixedSku({
    sku: "IOT-010",
    name: "IoT parceiro",
    suite: "CONNECT",
    kind: "IOT",
    amountCents: brl(199.9),
    billingCycle: "month",
    costReferenceCents: brl(65),
    commercialAvailability: "FEATURE_FLAGGED",
    revenueRecognition: "SUBSCRIPTION",
    portfolioSuiteId: "connect",
    sourceSection: IOT_SECTION,
  }),
];

export const API_CATALOG: CatalogItem[] = [
  fixedSku({
    sku: "API-001",
    name: "API Starter",
    suite: "API",
    kind: "API",
    amountCents: brl(799),
    billingCycle: "month",
    costReferenceCents: brl(180),
    commercialAvailability: "DISABLED",
    revenueRecognition: "SUBSCRIPTION",
    portfolioSuiteId: "data",
    sourceSection: IOT_SECTION,
  }),
  fixedSku({
    sku: "API-002",
    name: "API Growth",
    suite: "API",
    kind: "API",
    amountCents: brl(2499),
    billingCycle: "month",
    costReferenceCents: brl(600),
    commercialAvailability: "DISABLED",
    revenueRecognition: "SUBSCRIPTION",
    portfolioSuiteId: "data",
    sourceSection: IOT_SECTION,
  }),
  fixedSku({
    sku: "API-003",
    name: "API Enterprise",
    suite: "API",
    kind: "API",
    amountCents: brl(4999),
    billingCycle: "month",
    costReferenceCents: brl(1300),
    commercialAvailability: "DISABLED",
    revenueRecognition: "SUBSCRIPTION",
    portfolioSuiteId: "data",
    sourceSection: IOT_SECTION,
  }),
  fixedSku({
    sku: "API-004",
    name: "Implantação API Enterprise",
    suite: "API",
    kind: "API",
    amountCents: brl(7500),
    billingCycle: "once",
    unit: "única",
    costReferenceCents: brl(4000),
    commercialAvailability: "DISABLED",
    revenueRecognition: "SUBSCRIPTION",
    portfolioSuiteId: "data",
    sourceSection: IOT_SECTION,
  }),
];
