import { serviceSku } from "./catalog-helpers";
import type { CatalogItem } from "./types";

/** Tabela SRV-001 … SRV-024 — referências do piloto. Prestador define o preço. */
export const SERVICE_CATALOG: CatalogItem[] = [
  serviceSku({ sku: "SRV-001", name: "Banho", tutorReais: 74.9, baseReais: 70, eccopetRevenueReais: 13.3 }),
  serviceSku({ sku: "SRV-002", name: "Tosa / grooming", tutorReais: 99.9, baseReais: 95, eccopetRevenueReais: 16.3 }),
  serviceSku({ sku: "SRV-003", name: "Grooming móvel", tutorReais: 159.9, baseReais: 155, eccopetRevenueReais: 23.5 }),
  serviceSku({ sku: "SRV-004", name: "Creche / daycare", tutorReais: 89.9, baseReais: 85, eccopetRevenueReais: 15.1 }),
  serviceSku({ sku: "SRV-005", name: "Hotel por diária", tutorReais: 129.9, baseReais: 125, eccopetRevenueReais: 19.9 }),
  serviceSku({ sku: "SRV-006", name: "Pet sitting", tutorReais: 69.9, baseReais: 65, eccopetRevenueReais: 12.7 }),
  serviceSku({ sku: "SRV-007", name: "Hospedagem domiciliar", tutorReais: 119.9, baseReais: 115, eccopetRevenueReais: 18.7 }),
  serviceSku({ sku: "SRV-008", name: "Passeio", tutorReais: 54.9, baseReais: 50, eccopetRevenueReais: 10.9 }),
  serviceSku({ sku: "SRV-009", name: "Adestramento por sessão", tutorReais: 169.9, baseReais: 165, eccopetRevenueReais: 24.7 }),
  serviceSku({ sku: "SRV-010", name: "Consulta comportamental", tutorReais: 249.9, baseReais: 245, eccopetRevenueReais: 34.3 }),
  serviceSku({ sku: "SRV-011", name: "Táxi pet local", tutorReais: 84.9, baseReais: 80, eccopetRevenueReais: 14.5 }),
  serviceSku({
    sku: "SRV-012",
    name: "Ambulância pet",
    tutorReais: 264.9,
    baseReais: 245.1,
    eccopetRevenueReais: 49.21,
    urgent: true,
  }),
  serviceSku({ sku: "SRV-013", name: "Traslado nacional", tutorReais: 949.9, baseReais: 945, eccopetRevenueReais: 118.3 }),
  serviceSku({
    sku: "SRV-014",
    name: "Documentação internacional",
    tutorReais: 1349.9,
    baseReais: 1345,
    eccopetRevenueReais: 166.3,
  }),
  serviceSku({ sku: "SRV-015", name: "Microchipagem", tutorReais: 139.9, baseReais: 135, eccopetRevenueReais: 21.1 }),
  serviceSku({
    sku: "SRV-016",
    name: "Relocation internacional",
    tutorReais: 1849.9,
    baseReais: 1845,
    eccopetRevenueReais: 226.3,
  }),
  serviceSku({ sku: "SRV-017", name: "Lar temporário / diária", tutorReais: 69.9, baseReais: 65, eccopetRevenueReais: 12.7 }),
  serviceSku({ sku: "SRV-018", name: "Adoção assistida", tutorReais: 189.9, baseReais: 185, eccopetRevenueReais: 27.1 }),
  serviceSku({ sku: "SRV-019", name: "Cremação individual", tutorReais: 679.9, baseReais: 675, eccopetRevenueReais: 85.9 }),
  serviceSku({ sku: "SRV-020", name: "Memorial digital premium", tutorReais: 79.9, baseReais: 75, eccopetRevenueReais: 13.9 }),
  serviceSku({
    sku: "SRV-021",
    name: "Cuidados paliativos domiciliares",
    tutorReais: 399.9,
    baseReais: 395,
    eccopetRevenueReais: 52.3,
  }),
  serviceSku({ sku: "SRV-022", name: "Home care veterinário", tutorReais: 269.9, baseReais: 265, eccopetRevenueReais: 36.7 }),
  serviceSku({
    sku: "SRV-023",
    name: "Assistência emergencial de logística",
    tutorReais: 149.9,
    baseReais: 130.1,
    eccopetRevenueReais: 35.41,
    urgent: true,
  }),
  serviceSku({
    sku: "SRV-024",
    name: "Busca de animal perdido — operação local",
    tutorReais: 99.9,
    baseReais: 80.1,
    eccopetRevenueReais: 29.41,
    urgent: true,
  }),
];
