import { brl, fixedSku } from "./catalog-helpers";
import type { CatalogItem } from "./types";

const ONE_SECTION = "8. Planos de assinatura para tutores";
const PRO_SECTION = "9. Planos de assinatura para parceiros";

/** Billing One permanece FEATURE_FLAGGED — catálogo sem checkout funcional. */
export const ONE_CATALOG: CatalogItem[] = [
  fixedSku({
    sku: "ONE-000",
    name: "One Free",
    suite: "ONE",
    kind: "SUBSCRIPTION",
    amountCents: 0,
    billingCycle: "month",
    unit: "tutor / mês",
    costReferenceCents: brl(2.5),
    allowZero: true,
    commercialAvailability: "FEATURE_FLAGGED",
    portfolioSuiteId: "one",
    sourceSection: ONE_SECTION,
  }),
  fixedSku({
    sku: "ONE-001",
    name: "One Plus",
    suite: "ONE",
    kind: "SUBSCRIPTION",
    amountCents: brl(19.9),
    annualAmountCents: brl(199),
    billingCycle: "month",
    unit: "tutor / mês",
    costReferenceCents: brl(6.5),
    commercialAvailability: "FEATURE_FLAGGED",
    portfolioSuiteId: "one",
    sourceSection: ONE_SECTION,
  }),
  fixedSku({
    sku: "ONE-002",
    name: "One Care",
    suite: "ONE",
    kind: "SUBSCRIPTION",
    amountCents: brl(39.9),
    annualAmountCents: brl(399),
    billingCycle: "month",
    unit: "tutor / mês",
    costReferenceCents: brl(13.5),
    commercialAvailability: "FEATURE_FLAGGED",
    portfolioSuiteId: "one",
    sourceSection: ONE_SECTION,
  }),
  fixedSku({
    sku: "ONE-003",
    name: "One Family",
    suite: "ONE",
    kind: "SUBSCRIPTION",
    amountCents: brl(69.9),
    annualAmountCents: brl(699),
    billingCycle: "month",
    unit: "tutor / mês",
    costReferenceCents: brl(22),
    commercialAvailability: "FEATURE_FLAGGED",
    portfolioSuiteId: "one",
    sourceSection: ONE_SECTION,
  }),
  fixedSku({
    sku: "ONE-004",
    name: "One Global",
    suite: "ONE",
    kind: "SUBSCRIPTION",
    amountCents: brl(99.9),
    annualAmountCents: brl(999),
    billingCycle: "month",
    unit: "tutor / mês",
    costReferenceCents: brl(34),
    commercialAvailability: "FEATURE_FLAGGED",
    portfolioSuiteId: "one",
    sourceSection: ONE_SECTION,
  }),
  fixedSku({
    sku: "ONE-010",
    name: "Add-on IA",
    suite: "ONE",
    kind: "ADDON",
    amountCents: brl(14.9),
    billingCycle: "month",
    unit: "mês",
    costReferenceCents: brl(4.5),
    commercialAvailability: "FEATURE_FLAGGED",
    portfolioSuiteId: "one",
    sourceSection: ONE_SECTION,
  }),
  fixedSku({
    sku: "ONE-011",
    name: "Add-on emergência digital",
    suite: "ONE",
    kind: "ADDON",
    amountCents: brl(9.9),
    billingCycle: "month",
    unit: "mês",
    costReferenceCents: brl(3),
    commercialAvailability: "FEATURE_FLAGGED",
    portfolioSuiteId: "one",
    sourceSection: ONE_SECTION,
  }),
  fixedSku({
    sku: "ONE-012",
    name: "Add-on viagem",
    suite: "ONE",
    kind: "ADDON",
    amountCents: brl(19.9),
    billingCycle: "month",
    unit: "mês",
    costReferenceCents: brl(6),
    commercialAvailability: "FEATURE_FLAGGED",
    portfolioSuiteId: "one",
    sourceSection: ONE_SECTION,
  }),
  fixedSku({
    sku: "ONE-013",
    name: "Add-on IoT Connect",
    suite: "ONE",
    kind: "ADDON",
    amountCents: brl(19.9),
    billingCycle: "month",
    unit: "mês",
    costReferenceCents: brl(6),
    commercialAvailability: "FEATURE_FLAGGED",
    portfolioSuiteId: "connect",
    sourceSection: ONE_SECTION,
  }),
  fixedSku({
    sku: "ONE-014",
    name: "Armazenamento adicional",
    suite: "ONE",
    kind: "ADDON",
    amountCents: brl(5.9),
    billingCycle: "month",
    unit: "mês",
    costReferenceCents: brl(1.2),
    commercialAvailability: "FEATURE_FLAGGED",
    portfolioSuiteId: "one",
    sourceSection: ONE_SECTION,
  }),
];

export const PRO_CATALOG: CatalogItem[] = [
  fixedSku({
    sku: "PRO-001",
    name: "Pro Starter",
    suite: "PRO",
    kind: "SUBSCRIPTION",
    amountCents: brl(89.9),
    setupAmountCents: brl(249),
    billingCycle: "month",
    unit: "parceiro / mês",
    costReferenceCents: brl(24),
    commercialAvailability: "FEATURE_FLAGGED",
    portfolioSuiteId: "pro",
    sourceSection: PRO_SECTION,
  }),
  fixedSku({
    sku: "PRO-002",
    name: "Pro Growth",
    suite: "PRO",
    kind: "SUBSCRIPTION",
    amountCents: brl(229.9),
    setupAmountCents: brl(499),
    billingCycle: "month",
    unit: "parceiro / mês",
    costReferenceCents: brl(55),
    commercialAvailability: "FEATURE_FLAGGED",
    portfolioSuiteId: "pro",
    sourceSection: PRO_SECTION,
  }),
  fixedSku({
    sku: "PRO-003",
    name: "Pro Clinic",
    suite: "PRO",
    kind: "SUBSCRIPTION",
    amountCents: brl(399.9),
    setupAmountCents: brl(899),
    billingCycle: "month",
    unit: "clínica / mês",
    costReferenceCents: brl(105),
    commercialAvailability: "FEATURE_FLAGGED",
    portfolioSuiteId: "pro",
    sourceSection: PRO_SECTION,
  }),
  fixedSku({
    sku: "PRO-004",
    name: "Pro Enterprise",
    suite: "PRO",
    kind: "SUBSCRIPTION",
    amountCents: brl(1499.9),
    setupAmountCents: brl(3500),
    billingCycle: "month",
    unit: "enterprise / mês",
    costReferenceCents: brl(380),
    commercialAvailability: "FEATURE_FLAGGED",
    portfolioSuiteId: "pro",
    sourceSection: PRO_SECTION,
  }),
  fixedSku({
    sku: "PRO-010",
    name: "Usuário adicional",
    suite: "PRO",
    kind: "ADDON",
    amountCents: brl(19.9),
    billingCycle: "month",
    unit: "mês",
    costReferenceCents: brl(3),
    commercialAvailability: "FEATURE_FLAGGED",
    portfolioSuiteId: "pro",
    sourceSection: PRO_SECTION,
  }),
  fixedSku({
    sku: "PRO-011",
    name: "Unidade adicional",
    suite: "PRO",
    kind: "ADDON",
    amountCents: brl(119.9),
    billingCycle: "month",
    unit: "mês",
    costReferenceCents: brl(35),
    commercialAvailability: "FEATURE_FLAGGED",
    portfolioSuiteId: "pro",
    sourceSection: PRO_SECTION,
  }),
  fixedSku({
    sku: "PRO-012",
    name: "Suporte prioritário",
    suite: "PRO",
    kind: "ADDON",
    amountCents: brl(179.9),
    billingCycle: "month",
    unit: "mês",
    costReferenceCents: brl(60),
    commercialAvailability: "FEATURE_FLAGGED",
    portfolioSuiteId: "pro",
    sourceSection: PRO_SECTION,
  }),
  fixedSku({
    sku: "PRO-013",
    name: "Migração de dados",
    suite: "PRO",
    kind: "ADDON",
    amountCents: brl(899),
    billingCycle: "once",
    unit: "única",
    costReferenceCents: brl(500),
    commercialAvailability: "FEATURE_FLAGGED",
    portfolioSuiteId: "pro",
    sourceSection: PRO_SECTION,
  }),
  fixedSku({
    sku: "PRO-014",
    name: "Treinamento remoto",
    suite: "PRO",
    kind: "ADDON",
    amountCents: brl(349),
    billingCycle: "session",
    unit: "sessão",
    costReferenceCents: brl(150),
    commercialAvailability: "FEATURE_FLAGGED",
    portfolioSuiteId: "pro",
    sourceSection: PRO_SECTION,
  }),
  fixedSku({
    sku: "PRO-015",
    name: "White-label base",
    suite: "PRO",
    kind: "ADDON",
    amountCents: brl(5999),
    billingCycle: "month",
    unit: "mês",
    costReferenceCents: brl(1800),
    commercialAvailability: "FEATURE_FLAGGED",
    portfolioSuiteId: "pro",
    sourceSection: PRO_SECTION,
  }),
];
