import { defineEvent } from "./definitions";

export const AiEvents = {
  ASSISTANT_OPEN: defineEvent({
    event_name: "ai_assistant_open",
    category: "ai",
    action: "open",
    module: "ai",
  }),
  QUESTION: defineEvent({
    event_name: "ai_question_sent",
    category: "ai",
    action: "question",
    module: "ai",
  }),
  RESPONSE: defineEvent({
    event_name: "ai_response_received",
    category: "ai",
    action: "response",
    module: "ai",
  }),
  TOOL_USED: defineEvent({
    event_name: "ai_tool_used",
    category: "ai",
    action: "tool",
    module: "ai",
  }),
  ERROR: defineEvent({
    event_name: "ai_error",
    category: "ai",
    action: "error",
    module: "ai",
  }),
  LATENCY: defineEvent({
    event_name: "ai_response_time",
    category: "ai",
    action: "latency",
    module: "ai",
  }),
  CATALOG_VIEW: defineEvent({
    event_name: "ai_catalog_view",
    category: "ai",
    action: "view",
    module: "ai",
  }),
  PRODUCT_VIEW: defineEvent({
    event_name: "ai_product_view",
    category: "ai",
    action: "view",
    module: "ai",
  }),
  ADD_TO_CART: defineEvent({
    event_name: "ai_add_to_cart",
    category: "ai",
    action: "add_to_cart",
    module: "ai",
  }),
  CHECKOUT_STARTED: defineEvent({
    event_name: "ai_checkout_started",
    category: "ai",
    action: "checkout",
    module: "ai",
  }),
  PAYMENT_APPROVED: defineEvent({
    event_name: "ai_payment_approved",
    category: "ai",
    action: "payment",
    module: "ai",
  }),
  ENTITLEMENT_CREATED: defineEvent({
    event_name: "ai_entitlement_created",
    category: "ai",
    action: "entitlement",
    module: "ai",
  }),
  EXECUTION_STARTED: defineEvent({
    event_name: "ai_execution_started",
    category: "ai",
    action: "execution",
    module: "ai",
  }),
  EXECUTION_COMPLETED: defineEvent({
    event_name: "ai_execution_completed",
    category: "ai",
    action: "execution",
    module: "ai",
  }),
  REPORT_DOWNLOADED: defineEvent({
    event_name: "ai_report_downloaded",
    category: "ai",
    action: "report",
    module: "ai",
  }),
  REPURCHASE: defineEvent({
    event_name: "ai_repurchase",
    category: "ai",
    action: "repurchase",
    module: "ai",
  }),
  MODULE_OPEN: defineEvent({
    event_name: "ai_module_open",
    category: "ai",
    action: "open",
    module: "ai",
  }),
  PET_SELECTED: defineEvent({
    event_name: "ai_pet_selected",
    category: "ai",
    action: "select",
    module: "ai",
  }),
  ANALYSIS_STARTED: defineEvent({
    event_name: "ai_analysis_started",
    category: "ai",
    action: "analysis",
    module: "ai",
  }),
  ATTACHMENT_ADDED: defineEvent({
    event_name: "ai_attachment_added",
    category: "ai",
    action: "attachment",
    module: "ai",
  }),
  ANALYSIS_COMPLETED: defineEvent({
    event_name: "ai_analysis_completed",
    category: "ai",
    action: "analysis",
    module: "ai",
  }),
  ANALYSIS_FAILED: defineEvent({
    event_name: "ai_analysis_failed",
    category: "ai",
    action: "analysis",
    module: "ai",
  }),
  ARTIFACT_GENERATED: defineEvent({
    event_name: "ai_artifact_generated",
    category: "ai",
    action: "artifact",
    module: "ai",
  }),
  ARTIFACT_DOWNLOADED: defineEvent({
    event_name: "ai_artifact_downloaded",
    category: "ai",
    action: "artifact",
    module: "ai",
  }),
  FOLLOWUP_STARTED: defineEvent({
    event_name: "ai_followup_started",
    category: "ai",
    action: "followup",
    module: "ai",
  }),
  HEALTH_PROFILE_ADDED: defineEvent({
    event_name: "ai_health_profile_added",
    category: "ai",
    action: "profile",
    module: "ai",
  }),
  CROSS_MODULE_ACTION: defineEvent({
    event_name: "ai_cross_module_action",
    category: "ai",
    action: "cross_module",
    module: "ai",
  }),
} as const;