export const PLATFORM_EVENTS = {
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_SUSPENDED: "USER_SUSPENDED",
  USER_DELETED: "USER_DELETED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",

  PARTNER_APPROVED: "PARTNER_APPROVED",
  PARTNER_REJECTED: "PARTNER_REJECTED",
  PARTNER_SUSPENDED: "PARTNER_SUSPENDED",

  ONG_APPROVED: "ONG_APPROVED",
  ONG_REJECTED: "ONG_REJECTED",
  ONG_SUSPENDED: "ONG_SUSPENDED",

  PET_CREATED: "PET_CREATED",
  PET_UPDATED: "PET_UPDATED",

  ORDER_CREATED: "ORDER_CREATED",
  ORDER_PAID: "ORDER_PAID",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  ORDER_REFUNDED: "ORDER_REFUNDED",

  PAYMENT_CREATED: "PAYMENT_CREATED",
  PAYMENT_CONFIRMED: "PAYMENT_CONFIRMED",
  PAYMENT_FAILED: "PAYMENT_FAILED",

  PRODUCT_CREATED: "PRODUCT_CREATED",
  PRODUCT_APPROVED: "PRODUCT_APPROVED",
  PRODUCT_SUSPENDED: "PRODUCT_SUSPENDED",
  PRODUCT_STOCK_LOW: "PRODUCT_STOCK_LOW",

  SERVICE_CREATED: "SERVICE_CREATED",
  SERVICE_APPROVED: "SERVICE_APPROVED",
  SERVICE_SUSPENDED: "SERVICE_SUSPENDED",

  APPOINTMENT_CREATED: "APPOINTMENT_CREATED",
  APPOINTMENT_CANCELLED: "APPOINTMENT_CANCELLED",
  APPOINTMENT_COMPLETED: "APPOINTMENT_COMPLETED",

  POST_CREATED: "POST_CREATED",
  POST_REPORTED: "POST_REPORTED",
  POST_SUSPENDED: "POST_SUSPENDED",
  COMMENT_REPORTED: "COMMENT_REPORTED",
  COMMENT_SUSPENDED: "COMMENT_SUSPENDED",

  ADOPTION_REQUEST_CREATED: "ADOPTION_REQUEST_CREATED",
  ADOPTION_APPROVED: "ADOPTION_APPROVED",
  ADOPTION_REJECTED: "ADOPTION_REJECTED",

  DONATION_RECEIVED: "DONATION_RECEIVED",
  CAMPAIGN_CREATED: "CAMPAIGN_CREATED",
  CAMPAIGN_COMPLETED: "CAMPAIGN_COMPLETED",

  AI_REQUEST_CREATED: "AI_REQUEST_CREATED",
  AI_REQUEST_FAILED: "AI_REQUEST_FAILED",

  INTEGRATION_FAILED: "INTEGRATION_FAILED",
  WEBHOOK_RECEIVED: "WEBHOOK_RECEIVED",
  JOB_FAILED: "JOB_FAILED",
} as const;

export type PlatformEventType = (typeof PLATFORM_EVENTS)[keyof typeof PLATFORM_EVENTS];

export type PlatformEventInput = {
  type: PlatformEventType | string;
  actorId?: string;
  actorRole?: string;
  entityType?: string;
  entityId?: string;
  payload?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
  severity?: "info" | "low" | "medium" | "high" | "critical";
};

export type StoredPlatformEvent = PlatformEventInput & {
  id: string;
  createdAt: string;
};
