import type { Robot24h } from "../types";

export const CLIENT_ROBOTS: Robot24h[] = [
  { id: "cr1", name: "Robô da Vida do Pet", function: "Rotina, vacinas, consultas, alimentação", area: "Pet", status: "active", frequency: "Contínuo", lastRun: "Há 3 min", nextRun: "Contínuo", alerts: 1, actionsExecuted: 45, autonomy: "suggestion", operationalRisk: "low", aiRecommendation: "Agendar banho Luna em 5 dias" },
  { id: "cr2", name: "Robô de Saúde", function: "Vacinas, medicamentos, prontuário, exames", area: "Saúde", status: "active", frequency: "A cada 1h", lastRun: "Há 45 min", nextRun: "Em 15 min", alerts: 2, actionsExecuted: 28, autonomy: "approval_required", operationalRisk: "medium", aiRecommendation: "Vacina V10 Thor em dia ✓" },
  { id: "cr3", name: "Robô Financeiro Pessoal", function: "Gastos, assinaturas, cashback, cupons", area: "Financeiro", status: "active", frequency: "Diário", lastRun: "Hoje 08:00", nextRun: "Amanhã 08:00", alerts: 0, actionsExecuted: 12, autonomy: "monitoring", operationalRisk: "low" },
  { id: "cr4", name: "Robô de Integrações", function: "Redes sociais, agenda, wearables, IoT", area: "Integrações", status: "active", frequency: "A cada 30 min", lastRun: "Há 12 min", nextRun: "Em 18 min", alerts: 0, actionsExecuted: 67, autonomy: "auto_limited", operationalRisk: "medium" },
  { id: "cr5", name: "Robô de Lazer", function: "Passeios, eventos, parques, comunidades", area: "Lazer", status: "active", frequency: "Diário", lastRun: "Hoje 07:00", nextRun: "Amanhã 07:00", alerts: 0, actionsExecuted: 8, autonomy: "suggestion", operationalRisk: "low", aiRecommendation: "Feira pet domingo — Parque Ibirapuera" },
  { id: "cr6", name: "Robô de Marketplace", function: "Produtos, promoções, reposição, comparativos", area: "Marketplace", status: "active", frequency: "A cada 2h", lastRun: "Há 1h", nextRun: "Em 1h", alerts: 1, actionsExecuted: 34, autonomy: "suggestion", operationalRisk: "low", aiRecommendation: "Ração Golden — 15% off hoje" },
  { id: "cr7", name: "Robô Social", function: "Posts, hashtags, interações, comunidades", area: "Social", status: "paused", frequency: "A cada 4h", lastRun: "Ontem 20:00", nextRun: "Pausado", alerts: 0, actionsExecuted: 19, autonomy: "approval_required", operationalRisk: "low" },
  { id: "cr8", name: "Robô de IA Pessoal", function: "Resumos, alertas, recomendações, dúvidas", area: "IA", status: "active", frequency: "Contínuo", lastRun: "Há 1 min", nextRun: "Contínuo", alerts: 0, actionsExecuted: 156, autonomy: "auto_limited", operationalRisk: "low", aiRecommendation: "Resumo diário: Luna 8.5k passos" },
];

export const PARTNER_ROBOTS: Robot24h[] = [
  { id: "pr1", name: "Robô Financeiro", function: "Receitas, despesas, fluxo, inadimplência, margem", area: "Financeiro", status: "active", frequency: "Contínuo", lastRun: "Há 5 min", nextRun: "Contínuo", alerts: 2, actionsExecuted: 890, autonomy: "monitoring", operationalRisk: "high", aiRecommendation: "Inadimplência +0.3pp — revisar cobrança" },
  { id: "pr2", name: "Robô Comercial", function: "Vendas, leads, conversão, oportunidades", area: "Comercial", status: "active", frequency: "A cada 15 min", lastRun: "Há 8 min", nextRun: "Em 7 min", alerts: 1, actionsExecuted: 456, autonomy: "suggestion", operationalRisk: "medium", aiRecommendation: "23 clientes inativos 30+ dias" },
  { id: "pr3", name: "Robô de Estoque", function: "Estoque baixo, validade, ruptura, reposição", area: "Estoque", status: "active", frequency: "A cada 1h", lastRun: "Há 20 min", nextRun: "Em 40 min", alerts: 8, actionsExecuted: 234, autonomy: "approval_required", operationalRisk: "medium", aiRecommendation: "Repor Ração Golden — 40 un." },
  { id: "pr4", name: "Robô de Marketing", function: "Posts, campanhas, promoções, engajamento", area: "Marketing", status: "active", frequency: "A cada 2h", lastRun: "Há 30 min", nextRun: "Em 1h30", alerts: 0, actionsExecuted: 178, autonomy: "approval_required", operationalRisk: "low", aiRecommendation: "Campanha banho+tosa inativos" },
  { id: "pr5", name: "Robô de Integrações", function: "APIs, sync, marketplaces, redes sociais", area: "Integrações", status: "error", frequency: "A cada 5 min", lastRun: "Há 2h", nextRun: "Erro", alerts: 3, actionsExecuted: 1200, autonomy: "auto_limited", operationalRisk: "high", aiRecommendation: "ERP Totvs offline — reconectar" },
  { id: "pr6", name: "Robô Jurídico", function: "Contratos, LGPD, termos, pendências", area: "Jurídico", status: "active", frequency: "Diário", lastRun: "Hoje 06:00", nextRun: "Amanhã 06:00", alerts: 1, actionsExecuted: 45, autonomy: "monitoring", operationalRisk: "high" },
  { id: "pr7", name: "Robô Contábil", function: "Notas, impostos, calendário fiscal", area: "Contábil", status: "active", frequency: "Diário", lastRun: "Hoje 07:00", nextRun: "Amanhã 07:00", alerts: 2, actionsExecuted: 67, autonomy: "monitoring", operationalRisk: "high", aiRecommendation: "DAS maio — vence em 3 dias" },
  { id: "pr8", name: "Robô Administrativo", function: "Tarefas, equipe, processos, produtividade", area: "Admin", status: "active", frequency: "A cada 4h", lastRun: "Há 2h", nextRun: "Em 2h", alerts: 0, actionsExecuted: 89, autonomy: "suggestion", operationalRisk: "low" },
  { id: "pr9", name: "Robô de Agenda", function: "Consultas, conflitos, faltas, reagendamentos", area: "Agenda", status: "active", frequency: "A cada 30 min", lastRun: "Há 10 min", nextRun: "Em 20 min", alerts: 1, actionsExecuted: 312, autonomy: "auto_limited", operationalRisk: "medium" },
  { id: "pr10", name: "Robô AgroPet", function: "Produção, IoT, sensores, clima, rebanho", area: "AgroPet", status: "active", frequency: "A cada 1h", lastRun: "Há 45 min", nextRun: "Em 15 min", alerts: 2, actionsExecuted: 156, autonomy: "monitoring", operationalRisk: "medium", aiRecommendation: "Umidade solo abaixo do ideal" },
  { id: "pr11", name: "Robô de IA Empresarial", function: "Insights, demanda, riscos, resumos executivos", area: "IA", status: "active", frequency: "Contínuo", lastRun: "Há 2 min", nextRun: "Contínuo", alerts: 0, actionsExecuted: 567, autonomy: "auto_limited", operationalRisk: "low", aiRecommendation: "Junho: +12% faturamento previsto" },
];

export const NGO_ROBOTS: Robot24h[] = [
  { id: "nr1", name: "Robô de Campanhas Sociais", function: "Campanhas, engajamento, arrecadação, metas", area: "Campanhas", status: "active", frequency: "A cada 2h", lastRun: "Há 1h", nextRun: "Em 1h", alerts: 1, actionsExecuted: 89, autonomy: "approval_required", operationalRisk: "low", aiRecommendation: "Campanha Mel — 68% da meta" },
  { id: "nr2", name: "Robô de Métricas Sociais", function: "Adoções, resgates, doações, impacto", area: "Métricas", status: "active", frequency: "Diário", lastRun: "Hoje 08:00", nextRun: "Amanhã 08:00", alerts: 0, actionsExecuted: 45, autonomy: "monitoring", operationalRisk: "low" },
  { id: "nr3", name: "Robô de Novos Projetos", function: "Ideias, oportunidades, roadmap social", area: "Projetos", status: "active", frequency: "Semanal", lastRun: "Seg 09:00", nextRun: "Próx. Seg", alerts: 0, actionsExecuted: 12, autonomy: "suggestion", operationalRisk: "low" },
  { id: "nr4", name: "Robô de Adoção", function: "Animais, interessados, triagem, entrevistas", area: "Adoção", status: "active", frequency: "A cada 1h", lastRun: "Há 30 min", nextRun: "Em 30 min", alerts: 3, actionsExecuted: 234, autonomy: "approval_required", operationalRisk: "medium", aiRecommendation: "3 entrevistas pendentes" },
  { id: "nr5", name: "Robô de Resgate", function: "Urgências, localização, lares temporários", area: "Resgate", status: "active", frequency: "Contínuo", lastRun: "Há 5 min", nextRun: "Contínuo", alerts: 2, actionsExecuted: 67, autonomy: "auto_limited", operationalRisk: "high", aiRecommendation: "2 urgências ativas — ação imediata" },
  { id: "nr6", name: "Robô de Doações", function: "PIX, recorrências, transparência, metas", area: "Doações", status: "active", frequency: "A cada 30 min", lastRun: "Há 15 min", nextRun: "Em 15 min", alerts: 0, actionsExecuted: 178, autonomy: "monitoring", operationalRisk: "medium" },
  { id: "nr7", name: "Robô de Voluntários", function: "Agenda, tarefas, presença, produtividade", area: "Voluntários", status: "active", frequency: "A cada 4h", lastRun: "Há 1h", nextRun: "Em 3h", alerts: 0, actionsExecuted: 56, autonomy: "suggestion", operationalRisk: "low" },
  { id: "nr8", name: "Robô de IA Social", function: "Insights, campanhas, mensagens, divulgação", area: "IA", status: "active", frequency: "Contínuo", lastRun: "Há 1 min", nextRun: "Contínuo", alerts: 0, actionsExecuted: 345, autonomy: "auto_limited", operationalRisk: "low", aiRecommendation: "Posts antes/depois — 3x engajamento" },
];

export function getRobotsForProfile(category: "CLIENT" | "PARTNER" | "NGO"): Robot24h[] {
  if (category === "CLIENT") return CLIENT_ROBOTS;
  if (category === "NGO") return NGO_ROBOTS;
  return PARTNER_ROBOTS;
}
